aristanetworks/anta

- anta/inventory/__init__.py
- anta/inventory/models.py
- documentation/inventory.md
- documentation/inventory.models.md
- documentation/overview.md
- documentation/tests.md
- examples/inventory.yml
- pylintrc
- requirements.txt
Base to start implementation for #12
> feat: implement initial inventory module

- .github/workflows/test.yml
- anta/inventory/__init__.py
- anta/inventory/models.py
- examples/inventory.yml
- requirements-dev.txt
- tests/data/json_data.py
- tests/data/parametrize.py
- tests/data/utils.py
- tests/pytest.ini
- tests/units/antatests_test.py
- tests/units/inventory_models_test.py
- tests/units/inventory_test.py
```
----------- coverage: platform linux, python 3.9.9-final-0 -----------
Name                                                                      Stmts   Miss  Cover
---------------------------------------------------------------------------------------------
/home/tom/Projects/network-test-automation/anta/inventory/__init__.py       104     28    73%
/home/tom/Projects/network-test-automation/anta/inventory/exceptions.py       4      0   100%
/home/tom/Projects/network-test-automation/anta/inventory/models.py          30      1    97%
---------------------------------------------------------------------------------------------
TOTAL                                                                       138     29    79%
```
> ci(pytest): Add anta.inventory unit tests

- anta/inventory/__init__.py
Fix following problems:
-----------------------
- Method to detect if host is part of inventory
- Cast some variables for correct comparison
- Logging mechanism
New feature:
------------
- Add timeout option in Class init
> fix(inventory): Multiple fixes

- docs/requirements-and-installation.md
> doc: update installation process

- anta/inventory/models.py
```python
>>> inventory_anta = AntaInventory(
>>>   inventory_file='examples/inventory.yml',
>>>   username='ansible',
>>>   password='ansible',
>>>   timeout=0.5,
>>>   auto_connect=True
>>> )
>>> print(len(inventory_anta.get_inventory()))
6
```
> feat(inventory): Add support for len in InventoryDevices

- scripts/create-devices-inventory-from-cvp.py
update cvp script to output an inv file for the inv module
> update cvp script to output inv file

- .pre-commit-config.yaml
- anta/result_manager/__init__.py
- anta/result_manager/models.py
- anta/result_manager/report.py
- docs/api/README.md
- docs/api/inventory.md
- docs/api/inventory.models.md
- docs/api/result_manager.md
- docs/api/result_manager.models.md
- docs/api/result_manager.report.md
- docs/generate-functions-documentation.py
- requirements.txt
```
if __name__ == '__main__':
logging.disable(sys.maxsize)
print('Load inventory file')
inventory_anta = AntaInventory(
inventory_file='examples/inventory.yml',
username='ansible',
password='ansible',
timeout=0.5,
auto_connect=True
)
print('Run testing')
manager = ResultManager()
for device in inventory_anta.get_inventory():
result = verify_eos_version(
device=device, versions=['4.28.0F']
)
manager.add_test_result(result)
manager.add_test_result(
verify_eos_version(
device=device, versions=[
'4.27.3F-26379303.4273F (engineering build)']
)
)
manager.add_test_result(
verify_uptime(
device=device, minimum=1
)
)
print('Display result\n')
print(
manager.table_report(
sort_by='host',
reverse=False
)
)
f = open("report.txt", "a")
f.write(
manager.table_report(
sort_by='host',
reverse=False, …
```
> feat(report-manager): Initial report_manager implementation

- scripts/collect-sheduled-show-tech.py
update show tech collection to use inv
> update show tech collection to use inv

- scripts/collect-eos-commands.py
update collect commands script to use inv
> update collect commands script to use inv

- README.md
Update README file to use new inventory format as most of the scripts have been converted now.
> doc: Update to reflect inventory format

- anta/result_manager/models.py
- anta/tests/configuration.py
- anta/tests/hardware.py
- anta/tests/interfaces.py
- anta/tests/mlag.py
- anta/tests/multicast.py
- anta/tests/profiles.py
- anta/tests/routing/bgp.py
- anta/tests/routing/generic.py
- anta/tests/routing/ospf.py
- anta/tests/software.py
- anta/tests/system.py
- anta/tests/vxlan.py
- pylintrc
- feat(result-manager): Implement helpers to set status
- refactor(tests): Implement state helpers from TestResult + small updates in tests
- fix(result-manager): Correct typos
> feat(result-manager): Implement helpers to set status

- docs/usage-as-python-lib.md
To merge after #122 and rebasing
> Doc: Update test pattern in documentation

- anta/tests/interfaces.py
- tests/units/test_tests/test_configuration.py
List of impacted tests:
- [verify_illegal_lacp](https://github.com/arista-netdevops-community/network-test-automation/commit/1446a3e089bb04dba21c2ca9eeb1464b7902d8e9)
- [verify_portchannels](https://github.com/arista-netdevops-community/network-test-automation/commit/4a9bb30df12bf5f9e8b0ad447ca6bd3096915d41)
- [verify_interface_errors and verify_interfaces](https://github.com/arista-netdevops-community/network-test-automation/commit/eab9be92ffab86b5f1af0e378fada332238b3a37)
> fix(anta.tests): Fix some incorrect test reports

- .github/workflows/pr-triage.yml
Force usage of semantic syntax in PR
> make: Configure GH Action to lint PR title

- CNAME
Add a CNAM file to point to www.anta.ninjaa
> doc: Add CNAME setting

- .github/actions/rn-pr-labeler-action/action.yml
- .github/generate_release.py
- .github/release.yml
- .github/workflows/pull-request-rn-labeler.yml
- .github/workflows/release.yml
PR to implement release process:
> ci: Configure GH Action to publish release

- .github/workflows/pr-triage.yml
- .github/workflows/release.yml
- .github/workflows/website.yml
- [Fix typo in release workflow](https://github.com/arista-netdevops-community/network-test-automation/commit/268e35f1a59c305bbc7e3a774aeaa180b978f59b)
- [Add support for make and chore in PR title](https://github.com/arista-netdevops-community/network-test-automation/commit/4cff549cadfae6ca00f788c6d78b904cfbb034bb)
- [Configure CNAME for documentation](https://github.com/arista-netdevops-community/network-test-automation/commit/6907f009b951a68af652f2d338596030bc90e2fe)
> ci: Update some workflows

- CNAME
- README.md
- docs/README.md
- docs/cli/get-inventory-information.md
- docs/stylesheets/extra.material.css
- docs/usage-inventory-catalog.md
- mkdocs.yml
Update documentation to reflect new repository name
> doc: Update URLs with new repository name

- docs/api/report_manager.md
- docs/api/report_manager_models.md
- docs/api/result_manager_models.md
- docs/stylesheets/extra.material.css
- mkdocs.yml
- anta.reporter.*
- anta.result_manager.*
> doc: Add missing Python API modules

- Dockerfile
Implement initial [opencontainer labels](https://github.com/opencontainers/image-spec/blob/main/annotations.md)
> make: Add labels to docker image

- anta/cli/exec/commands.py
- anta/cli/exec/utils.py
- anta/cli/get/commands.py
- anta/inventory/models.py
- pyproject.toml
- fix(anta.cli): Improve 'anta exec collect-tech-support' using asyncssh
> fix(anta.cli): Make 'anta exec collect-tech-support' asynchronous

- README.md
- docs/advanced_usages/as-python-lib.md
- docs/advanced_usages/custom-tests.md
- docs/api/models.md
- docs/cli/debug.md
- docs/cli/nrfu.md
- docs/contribution.md
- docs/getting-started.md
- docs/requirements-and-installation.md
- docs/usage-inventory-catalog.md
- mkdocs.yml
- pyproject.toml
Documentation refactoring following PR #173
> doc: Refactor documentation with anta.models update

- anta/tests/interfaces.py
- tests/units/anta_tests/interfaces/data.py
- tests/units/anta_tests/interfaces/test_exc.py
> refactor(anta.tests): Refactor interfaces tests

- anta/tests/software.py
- tests/units/anta_tests/software/data.py
- tests/units/anta_tests/software/test_exc.py
> refactor(anta.tests): Move anta.tests.software to new format

- anta/tests/system.py
- tests/units/anta_tests/system/data.py
- tests/units/anta_tests/system/test_exc.py
> refactor(anta.tests): Move anta.tests.system to new structure

- anta/tests/mlag.py
- tests/units/anta_tests/mlag/data.py
- tests/units/anta_tests/mlag/test_exc.py
> refactor(anta.tests): Refactor mlag tests

- anta/decorators.py
- anta/models.py
- anta/tests/routing/bgp.py
- tests/units/anta_tests/routing/bgp/data.py
- tests/units/anta_tests/routing/bgp/test_exc.py
- tests/units/anta_tests/system/data.py
- tests/units/anta_tests/system/test_exc.py
This PR also fixes the BGP decorator
However two questions for the future:
1. is it useful (we usually call the same command twice..)
2. For now it is being skipped in tests (cf patched decorator voodoo-ninja)
> refactor(anta.tests): Move routing/bgp to new structure and add pytest

- anta/tests/profiles.py
- tests/units/anta_tests/mlag/data.py
- tests/units/anta_tests/profiles/data.py
- tests/units/anta_tests/profiles/test_exc.py
- tests/units/anta_tests/vxlan/data.py
> refactor(anta.tests): Refactor TCAM and UFT profiles

- .pre-commit-config.yaml
- anta/tests/logging.py
- docs/api/tests.logging.md
- mkdocs.yml
- tests/units/anta_tests/logging/data.py
- tests/units/anta_tests/logging/test_exc.py
Hello,
Please review this PR for new logging test cases.
Thanks
> feat(anta.tests): Add new logging test cases

- .pre-commit-config.yaml
- anta/models.py
- anta/tests/hardware.py
- anta/tests/routing/bgp.py
- tests/units/anta_tests/hardware/data.py
- tests/units/anta_tests/hardware/test_exc.py
- tests/units/anta_tests/routing/bgp/data.py
> feat: Change hardware tests for AVD

- anta/decorators.py
- anta/tests/routing/bgp.py
Hello,
PR to fix the decorators for BGP and hardware tests. #199
> fix(anta): Fix decorators for proper nrfu results

- anta/models.py
- anta/result_manager/models.py
- anta/tools/pydantic.py
- docs/api/tests.logging.md
Hello,
Added a few things for better output in AVD.
> fix(anta): Added minor stuff for AVD integration

- anta/cli/exec/commands.py
- anta/cli/exec/utils.py
- docs/cli/exec.md
> feat(anta.cli): added latest option to collect-tech-support

- anta/inventory/models.py
- anta/tests/logging.py
> fix(anta.tests): do not send 'show logging |' to EOS

- anta/cli/utils.py
- anta/runner.py
- anta/tests/interfaces.py
- anta/tests/stp.py
- anta/tools/get_value.py
- docs/api/tests.md
- docs/api/tests.stp.md
- examples/tests.yaml
- mkdocs.yml
- tests/units/anta_tests/interfaces/data.py
- tests/units/anta_tests/interfaces/test_exc.py
- tests/units/anta_tests/stp/data.py
- tests/units/anta_tests/stp/test_exc.py
Hello,
PR to add a few STP test cases and fix documentation.
Thanks
> feat(anta.tests): Add new STP test cases

- .github/workflows/code-testing.yml
- docs/api/inventory.models.md
Fix mkdocs issue not able to loads old inventory class.
> doc: Fix code documentation for inventory models

- anta/tests/connectivity.py
- docs/api/tests.connectivity.md
- docs/api/tests.md
- examples/tests.yaml
- mkdocs.yml
- tests/units/anta_tests/connectivity/data.py
- tests/units/anta_tests/connectivity/test_exc.py
Hello,
Please review and test this PR for new connectivity tests.
Thank you
> feat(anta.tests): New connectivity tests

- anta/__init__.py
- anta/cli/__init__.py
- anta/cli/exec/utils.py
- anta/cli/get/commands.py
- anta/device.py
- anta/inventory/__init__.py
- anta/loader.py
- anta/runner.py
- feat(anta): Introduce ANTA_DEBUG env var
- refactor(anta.device): implement __rich_repr__
- feat(anta.inventory): inherit from dict
> refactor(anta): AntaInventory inherit from dict

- .pre-commit-config.yaml
- anta/cli/__init__.py
- anta/cli/nrfu/commands.py
- anta/cli/utils.py
- anta/result_manager/__init__.py
- docs/cli/overview.md
- pyproject.toml
Fixes #192  (even if apparently I can't even name my branches right!)
Behavior tested locally with the various new CLI flags
> feat: Implement returning error code to anta functions

- .pre-commit-config.yaml
- anta/tests/mlag.py
- examples/tests.yaml
- tests/units/anta_tests/mlag/data.py
- tests/units/anta_tests/mlag/test_exc.py
Hello,
Please review and test these updated/new MLAG tests.
Thank you
> feat(anta.tests): MLAG tests update

- anta/tests/system.py
- tests/units/anta_tests/system/data.py
Fixes #258
cf test for more info
> fix: Make VerifyAgentLogs less verbose

- anta/cli/__init__.py
- anta/cli/exec/commands.py
- anta/cli/exec/utils.py
- anta/cli/utils.py
- docs/cli/exec.md
- pyproject.toml
- tests/data/test_inventory.yml
- tests/data/test_snapshot_commands.yml
- tests/lib/utils.py
- tests/units/cli/exec/test_commands.py
> fix(anta.cli)!: anta exec collect-tech-support --configure

- anta/cli/nrfu/commands.py
- docs/cli/nrfu.md
> refactor(anta.cli): Make anta nrfu text --skip-error a proper flag

- anta/cli/__init__.py
- anta/cli/debug/commands.py
- anta/cli/get/commands.py
- anta/cli/utils.py
- anta/models.py
- anta/reporter/__init__.py
- anta/result_manager/__init__.py
- anta/tools/pydantic.py
- anta_inventory/inventory-custom_container.yml
- anta_inventory/inventory.yml
- custom/inventory.yml
- pyproject.toml
- tests/data/test_catalog.yml
- tests/data/test_inventory.yml
- tests/lib/fixture.py
- tests/lib/utils.py
- tests/units/cli/debug/test_commands.py
- tests/units/cli/exec/test_commands.py
- tests/units/cli/exec/test_utils.py
- tests/units/cli/get/test_commands.py
- tests/units/cli/test__init__.py
- tests/units/reporter/test__init__.py
- tests/units/result_manager/test__init__.py
First PR of several to catch up on unit tests..
> test: Add unit tests across the repo

- .github/release.md
Create a documentation to use for release management
> doc: Add note for manual release of a package

- .github/workflows/code-testing.yml
- .github/workflows/pr-triage.yml
- Add an action to assign project to all new PRs
- Add an action to add comment in PR if documentation is missing
> ci: Update workflows for new features

- .github/workflows/code-testing.yml
- .github/workflows/pr-triage.yml
Reverts arista-netdevops-community/anta#327
> Revert "ci: Update workflows for new features"

- .github/workflows/code-testing.yml
Add a step to comment PR if documentation folder is not updated
> ci: Add comment if docs/ is not updated

- anta/reporter/__init__.py
Update column name to `Device` instead of `Device IP` since device name is
displayed if configured
> fix(anta): Update column name for device in nrfu table

- anta/tests/interfaces.py
- tests/units/anta_tests/interfaces/data.py
Update VerifyIntefaceErrors test with proper results.
Fixes: #343
> fix(anta.tests): Update VerifyInterfaceErrors test with proper results

- anta/tests/stp.py
- tests/units/anta_tests/interfaces/data.py
- tests/units/anta_tests/stp/data.py
Update STP AntaTemplate tests for better results output.
Fixes: #334
> fix(anta.tests): Update STP AntaTemplate tests

- docs/faq.md
- docs/requirements-and-installation.md
- mkdocs.yml
- pyproject.toml
Added note about urllib3 ImportError to the newly created FAQ.
Fixes: #331
> doc: Added FAQ page + note about urllib3

- .github/workflows/on-demand.yml
- .github/workflows/release.yml
- Link documentation jobs to Pypi
- Add a on demand workflow to validate new platform support for docker
> ci: Update release workflow to link jobs

- .github/pull_request_template.md
Add a PR template with a tasklist to help people when submitting their PR
Checklist:
```
```
> chore: add PR template to help community

- anta/tests/connectivity.py
- anta/tests/interfaces.py
- anta/tests/routing/generic.py
- examples/tests.yaml
- tests/units/anta_tests/routing/test_generic.py
- tests/units/anta_tests/test_connectivity.py
- tests/units/anta_tests/test_interfaces.py
Added the following tests:
- VerifyLLDPNeighbors
- VerifyRoutingTableEntry
Update:
- VerifyInterfacesStatus
> feat(anta.tests)!: Added new tests + Update VerifyInterfacesStatus

- anta/tests/interfaces.py
- examples/tests.yaml
- tests/units/anta_tests/test_interfaces.py
title
required for AVD integration
> feat(anta.tests)!: Support disabled (admin-down) interfaces for VerifyInterfaceStatus

- docs/faq.md
- docs/getting-started.md
* Additionally, fix couple of doc issues reported by @ksator 
Fixes #395
> doc: Add FAQ for Pyopenssl issue

- anta/cli/debug/commands.py
- tests/units/cli/debug/test_commands.py
> fix(anta.cli): Catch command failure for debug commands

- anta/models.py
- anta/tests/connectivity.py
- anta/tests/interfaces.py
- anta/tests/routing/bgp.py
- anta/tests/routing/generic.py
- anta/tests/stp.py
- tests/units/anta_tests/test_connectivity.py
- tests/units/cli/debug/test_commands.py
- tests/units/cli/exec/test_utils.py
> feat(anta.tests): Add repeat option in VerifyReachability test

- anta/custom_types.py
- anta/tests/interfaces.py
- tests/units/anta_tests/test_interfaces.py
Update the `Interface` custom type to support sub-interfaces.
> fix(anta.tests): Update Interface custom type

- anta/models.py
- anta/tests/stp.py
- tests/units/anta_tests/test_stp.py
> refactor(anta.tests): Refactor STP tests for better logic and coverage

- docs/contribution.md
- docs/requirements-and-installation.md
- pyproject.toml
> bump: ANTA v0.10.0

- .github/workflows/code-testing.yml
- pyproject.toml
> ci: Add python 3.12 support

- tests/units/anta_tests/routing/test_ospf.py
> test: Add OSPF tests when no OSPF is configured

- anta/reporter/__init__.py
- pyproject.toml
- tests/lib/utils.py
- tests/units/cli/debug/test_commands.py
- tests/units/reporter/test__init__.py
- tests/units/result_manager/test__init__.py
> test: Add coverage for reporter

- .pre-commit-config.yaml
- anta/runner.py
- anta/tools/misc.py
- pyproject.toml
> ci: Fix runner code for gather

- anta/cli/check/commands.py
- tests/units/cli/check/__init__.py
- tests/units/cli/check/test_commands.py
> test: Fix anta check catalog CLI output and test

- docs/usage-inventory-catalog.md
> doc: Fix wrong test name

- anta/reporter/__init__.py
show_lines set to True to show lines between table rows for readability
> feat: Show lines between table rows for readability

- anta/tests/software.py
- examples/tests.yaml
- tests/units/anta_tests/test_software.py
> fix(anta.tests): Add quotes around version name in VerifyEOSVersion

- anta/__init__.py
- anta/catalog.py
- anta/models.py
- anta/result_manager/__init__.py
- anta/result_manager/models.py
- anta/runner.py
- anta/tools/misc.py
- tests/data/syntax_error.py
- tests/data/test_catalog_with_syntax_error_module.yml
- tests/units/result_manager/test_models.py
- tests/units/test_catalog.py
- tests/units/test_device.py
- tests/units/tools/test_misc.py
> fix: improve various logs

- .devcontainer/devcontainer.json
- .devcontainer/startup.sh
- .vscode/settings.json
Add a devcontainer configuration for building a consistent development environment for new contributors or PR review with codespace.
> chore: Add a devcontainer environment for remote development

- anta/custom_types.py
- anta/tests/security.py
- anta/tools/utils.py
- examples/tests.yaml
- tests/units/anta_tests/test_security.py
Add the test case to verify the ssl certificate expiry, subject name, encryption type and size.
Run the testcase by adding catalog as below:
```
anta.tests.security:
- VerifyAPISSLCertificate:
certificates:
- certificate_name: ARISTA_SIGNING_CA.crt
expiry_threshold: 30
common_name: AristaIT-ICA ECDSA Issuing Cert Authority
encryption_algorithm: ECDSA
key_size: 256
- certificate_name: ARISTA_ROOT_CA.crt
expiry_threshold: 30
common_name: Arista Networks Internal IT Root Cert Authority
encryption_algorithm: RSA
key_size: 4096
```
1. Testcase pass when all details are correct:
```
All tests results                                                      
┏━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Device  ┃ Test …
```
> feat(anta.tests): Added test case for SSL certificate status as VerifyCertificateStatus

- tests/units/tools/test_utils.py
Added the unit tests for get_failed_logs function.
Fixes #520
> feat(anta): Add unit tests for get_failed_logs function

- docs/contribution.md
- docs/requirements-and-installation.md
- pyproject.toml
> bump: Version 0.12.0 -> 0.13.0

- pyproject.toml
Temporary fix for griffe issue cf https://github.com/arista-netdevops-community/anta/actions/runs/8143318981/job/22254892779 failed run
> ci: Fix griffe requirement because issue

- anta/result_manager/__init__.py
- docs/usage-inventory-catalog.md
- mkdocs.yml
- pyproject.toml
> ci: Remove griffe version lock and fix other mkdocs stuff

- docs/README.md
- docs/api/tests.aaa.md
- docs/api/tests.bfd.md
- docs/api/tests.configuration.md
- docs/api/tests.connectivity.md
- docs/api/tests.field_notices.md
- docs/api/tests.greent.md
- docs/api/tests.hardware.md
- docs/api/tests.interfaces.md
- docs/api/tests.lanz.md
- docs/api/tests.logging.md
- docs/api/tests.mlag.md
- docs/api/tests.multicast.md
- docs/api/tests.profiles.md
- docs/api/tests.ptp.md
- docs/api/tests.routing.bgp.md
- docs/api/tests.routing.generic.md
- docs/api/tests.routing.ospf.md
- docs/api/tests.security.md
- docs/api/tests.services.md
- docs/api/tests.snmp.md
- docs/api/tests.software.md
- docs/api/tests.stp.md
- docs/api/tests.system.md
- docs/api/tests.vlan.md
- docs/api/tests.vxlan.md
- docs/overrides/partials/content.html
- docs/templates/python/material/docstring.html
Look at this nice doc
+ table after title to make @mtache happy
> doc: More doc cleaning for tests

- .github/workflows/main-doc.yml
As described in the issue
Fixes #572
> ci: Generate doc all the time

- docs/faq.md
- docs/overrides/partials/toc-item.html
> doc: Nicer faq (last commit)

- anta/tests/interfaces.py
Update skip decorators for interface tests.
> fix(anta.tests): Update skip decorator for interface tests

- tests/units/anta_tests/test_field_notices.py
- tests/units/cli/exec/test_utils.py
- tests/units/cli/get/test_commands.py
- tests/units/cli/test__init__.py
- tests/units/test_models.py
> test: Add tests

- examples/README.md
> doc: Fix examples/README.md links

- anta/device.py
> fix: avoid performance regression of cryptography 37.0.x

- .pre-commit-config.yaml
format can prevent some check errors
> ci: Revert ruff format and ruff check

- .pre-commit-config.yaml
Reverts arista-netdevops-community/anta#627
https://docs.astral.sh/ruff/formatter/#sorting-imports
> Revert "ci: Revert ruff format and ruff check"

- docs/contribution.md
- docs/requirements-and-installation.md
- pyproject.toml
*  feat(anta)!: `-t` CLI option is now `--test` and not `--tags` by @mtache in https://github.com/arista-netdevops-community/anta/pull/622
* chore(anta)!: Remove support for Python 3.8 by @carl-baillargeon in https://github.com/arista-netdevops-community/anta/pull/604
* feat(anta): improve ANTA for high scale NRFU by @mtache in https://github.com/arista-netdevops-community/anta/pull/622
* feat(anta.tests): PtpGMStatus, PtpLockStatus, PtpModeStatus, PtpOffset, PtpPortModeStatus by @BarikiVarshitha in https://github.com/arista-netdevops-community/anta/pull/564
* feat(anta.tests): Add OSPF Max LSA Test by @klorfevre in https://github.com/arista-netdevops-community/anta/pull/602
* feat(anta.cli): `anta nrfu` enchancements: add `--device` and `--test` to filter tests and `--hide …
> bump: Version 0.13.0 -> 0.14.0

- docs/README.md
- docs/cli/overview.md
> doc: Remove v0.11.0 warning

- anta/custom_types.py
- anta/reporter/__init__.py
- anta/tests/interfaces.py
- anta/tests/security.py
- anta/tools.py
- tests/data/ansible_inventory_unknown_yaml_tag.yml
- tests/units/anta_tests/test_aaa.py
- tests/units/anta_tests/test_field_notices.py
- tests/units/anta_tests/test_interfaces.py
- tests/units/anta_tests/test_logging.py
- tests/units/anta_tests/test_security.py
- tests/units/anta_tests/test_services.py
- tests/units/anta_tests/test_software.py
- tests/units/cli/get/test_utils.py
- tests/units/reporter/test__init__.py
- tests/units/test_custom_types.py
> test: Add some more test coverage

- anta/cli/debug/utils.py
- tests/units/cli/debug/test_commands.py
- tests/units/cli/nrfu/test__init__.py
- tests/units/cli/nrfu/test_commands.py
> test: More CLI coverage

- docs/requirements-and-installation.md
> doc: Details on using EOS eAPI and AVD-ANTA version dependency

- Dockerfile
- anta/catalog.py
- anta/cli/exec/utils.py
- anta/cli/utils.py
- anta/custom_types.py
- anta/tests/field_notices.py
- docs/faq.md
- docs/stylesheets/extra.material.css
- tests/units/cli/nrfu/test_commands.py
- tests/units/test_models.py
* Refactor several pieces of code:
* remove commented out
* Fix FAQ in doc
> refactor: Fix FAQ and other pieces of code

- .devcontainer/startup.sh
Update devcontainer startup script to install anta cli package since it is
a package on its own starting v0.14.0
> chore: Update devcontainer startup script to install anta cli

- .github/workflows/code-testing.yml
> ci: Remove blocked actions

- .sonarcloud.properties
Add a .sonarcloud.properties file to use the analysis better
> ci: Test sonarcloud

- .arista/secret_allowlist.yaml
Implement Arista secret-scanner allow list for passed examples in doc
> ci: Allow-list for secret-scanner

- .github/workflows/secret-scanner.yml
follow recommendation from aristanetwork org - the scanner will prevent secrets to be committed to the main branch.
> ci: Opt-in for Secret-scanner workflow

- .github/release.md
- Dockerfile
- anta/__init__.py
- anta/cli/debug/utils.py
- docs/README.md
- docs/contribution.md
- docs/faq.md
- docs/requirements-and-installation.md
- docs/troubleshooting.md
- docs/usage-inventory-catalog.md
Remove all references to `arista-netdevops-community` and replace by `aristanetworks`
Partial fix for #697
> doc: Update all references to old GH org

- docs/README.md
- docs/advanced_usages/custom-tests.md
- docs/cli/nrfu.md
- docs/usage-inventory-catalog.md
- mkdocs.yml
- pyproject.toml
Activate [mkdocs lightbox JS plugin](https://github.com/blueswen/mkdocs-glightbox) for loading images
> doc: Use lightbox JS for images

- docs/overrides/main.html
> doc: Remove moving banner from doc

- anta/__init__.py
When ANTA_DEBUG is set, set the env variable recommended in Python doc
Fixes #663
> feat(anta): Enable asyncio DEBUGs when ANTA_DEBUG is true

- anta/tests/stun.py
- examples/tests.yaml
- tests/units/anta_tests/test_stun.py
Added testcase to validate STUN server status.
Fixes #711
> feat(anta.tests): Added testcase to validate STUN server status

- docs/requirements-and-installation.md
AVD now installs ANTA (yay)
Fixes #721
> doc: Remove special note for AVD

- .github/workflows/sonar.yml
for now the PRs do not show up in sonarcloud. This is an attempt to fix it
NOTE: this may break main analysis during trial and error
> ci: Test for PR info

- docs/cli/overview.md
> doc: correct environment example

- .vscode/settings.json
> chore: Update VSCode settings.json for Ruff

- docs/usage-inventory-catalog.md
> doc: Fix merge_catalogs script

- tests/units/cli/nrfu/test_commands.py
Add a unit test for `anta nrfu --hide success md-report`.
> test(anta): Add extra unit test for md-report

- anta/reporter/__init__.py
- anta/reporter/csv_reporter.py
- anta/reporter/md_reporter.py
- anta/result_manager/__init__.py
- anta/tools.py
- tests/units/reporter/test_csv.py
- tests/units/result_manager/test__init__.py
- tests/units/test_tools.py
> refactor(anta): Move conversion of categories to reporters

- anta/catalog.py
- anta/runner.py
- tests/units/test_catalog.py
> refactor(anta): Cleanup unused code

- anta/tests/flow_tracking.py
> fix(anta.tests): Skip VerifyHardwareFlowTrackerStatus for cEOSLab and vEOS-lab

- mkdocs.yml
> ci: Clean up duplicate plugins in mkdocs.yml (and sort)

- anta/input_models/services.py
- anta/tests/services.py
- docs/api/tests.services.md
- tests/units/anta_tests/test_services.py
Refactor VerifyDNSServers test for nicer failure message 
Related to #587 #388
> refactor(anta): Refactor VerifyDNSServers test for nicer failure message 

- anta/input_models/bfd.py
- anta/tests/bfd.py
- docs/api/tests.bfd.md
- tests/units/anta_tests/test_bfd.py
Refactoring BFD tests module to address the following issues:
- #809
- #587
- #388
> fix(anta.tests): Cleaning up BFD tests module

- docs/faq.md
> doc: Add AAA FAQ entry for ANTA user

- anta/device.py
- anta/result_manager/__init__.py
- anta/runner.py
- anta/tests/connectivity.py
- asynceapi/device.py
- pyproject.toml
- tests/benchmark/conftest.py
- tests/benchmark/test_anta.py
- tests/benchmark/test_reporter.py
- tests/benchmark/test_runner.py
- tests/units/cli/nrfu/test_commands.py
- **refactor(anta.tests): use list comprehension**
- **test(anta): add benchmarks for reporters**
> test(anta): Add benchmarks for reporters

- pyproject.toml
> chore(anta): Update RESPX

- docs/contribution.md
- docs/requirements-and-installation.md
- pyproject.toml
> bump: Version 1.1.0 -> 1.2.0

- .github/workflows/release.yml
> ci: Remove release coverage badge job

- anta/cli/nrfu/utils.py
- anta/constants.py
- anta/reporter/__init__.py
- anta/reporter/csv_reporter.py
- anta/reporter/md_reporter.py
- anta/result_manager/__init__.py
- tests/data/test_md_report.md
- tests/units/reporter/test_md_reporter.py
- tests/units/result_manager/test__init__.py
- Remove sorting out of the Markdown reporter
- Added `ResultManager.sort`
- Sort `ResultManager` stats properties by default
> fix(anta): Fix various issues in CSV and Markdown reporters

- anta/reporter/__init__.py
- docs/templates/python/material/class.html.jinja
> doc: Sometimes decorators are not functions

- anta/tests/aaa.py
- tests/units/anta_tests/test_aaa.py
Updated failure messages for following tests
1. test_aaa.py
- VerifyTacacsServers
- VerifyTacacsServerGroups
- VerifyAuthenMethods 
- VerifyAuthzMethods
- VerifyAcctDefaultMethods
- VerifyAcctConsoleMethods
Fixes #587
> refactor(anta.tests): Nicer result failure messages for  AAA test module

- .github/workflows/code-testing.yml
cf title.we are getting warnings
> ci: Update ubuntu runner verison to latest

- anta/cli/utils.py
- anta/inventory/__init__.py
- anta/inventory/models.py
- docs/snippets/anta_nrfu_help.txt
- tests/data/test_inventory_large.json
- tests/data/test_inventory_medium.json
- tests/data/test_inventory_with_tags.json
- tests/data/test_inventory_with_tags.yml
- tests/units/inventory/test__init__.py
- tests/units/inventory/test_models.py
> feat(anta): Support JSON inventory

- anta/input_models/snmp.py
- anta/tests/snmp.py
- anta/tests/software.py
- anta/tests/stp.py
- anta/tests/stun.py
- anta/tests/system.py
- anta/tests/vlan.py
- tests/units/anta_tests/test_snmp.py
- tests/units/anta_tests/test_software.py
- tests/units/anta_tests/test_stp.py
- tests/units/anta_tests/test_stun.py
- tests/units/anta_tests/test_system.py
- tests/units/anta_tests/test_vlan.py
Updated test failure messages:
1. services
2. snmp
3. system
4. software
5. stp
6. stun
7. vlan
8. vxlan
> refactor(anta.tests): Updated test failure messages

- anta/input_models/flow_tracking.py
- anta/tests/flow_tracking.py
- anta/tests/hardware.py
- anta/tests/logging.py
- tests/units/anta_tests/test_flow_tracking.py
- tests/units/anta_tests/test_hardware.py
- tests/units/anta_tests/test_logging.py
Updated test failure messages for following testsuite:
1. Flow-tracking
2. Hardware
3. Logging
> refactor(anta): Updated test failure messages for multiple tests

- anta/input_models/path_selection.py
- anta/tests/mlag.py
- anta/tests/multicast.py
- anta/tests/path_selection.py
- tests/units/anta_tests/test_mlag.py
- tests/units/anta_tests/test_multicast.py
- tests/units/anta_tests/test_path_selection.py
1. Mlag
2. Multicast
3. path selection
> refactor(anta): Updated test failures message for MLAG, Multicast and path selection suite

- anta/tests/profiles.py
- anta/tests/ptp.py
- anta/tests/security.py
- tests/units/anta_tests/test_profiles.py
- tests/units/anta_tests/test_ptp.py
- tests/units/anta_tests/test_security.py
Updated test failure messages:
1. profiles
2. ptp
3. security
> refactor(anta.tests): Updated test failure messages - part2

- docs/cli/overview.md
> doc(anta.cli): Update CLI environment variables table

- anta/tests/security.py
- anta/tests/system.py
- anta/tests/vxlan.py
- examples/tests.yaml
Revert test descriptions that were updated during the refactoring.
> fix(anta.tests): Revert some test descriptions

- anta/input_models/logging.py
- anta/tests/logging.py
- docs/api/tests/logging.md
- examples/tests.yaml
- pyproject.toml
- tests/units/anta_tests/test_logging.py
Added test to search syslog for specific entries
Fixes #1077
> feat(anta.tests): Added test to search syslog for specific entries

- anta/cli/get/utils.py
- anta/tests/system.py
- examples/tests.yaml
> feat(anta.cli): Add possibility to render multiple examples for the same test

- .pre-commit-config.yaml
> ci: Skip mypy in pre-commit.ci to avoid timeout

- docs/contribution.md
- docs/requirements-and-installation.md
- pyproject.toml
> bump: Version 1.2.0 -> 1.3.0

- .pre-commit-config.yaml
- anta/tests/interfaces.py
- tests/units/anta_tests/test_interfaces.py
Updated docstring for VerifyInterfaceUtilization test
Fixes #1109
> doc(anta.tests): Updated docstrings for VerifyInterfaceUtilization test

- .github/workflows/sonar.yml
> ci: Update sonar.yml

- anta/result_manager/__init__.py
- tests/units/result_manager/test__init__.py
* Added merge_results function to the ResultManager's __init__.py.
* Added unit tests to verify the function.
Fixes #1093
> feat(anta): Add merge_results() to merge ResultManager's

- .github/workflows/sonar.yml
Debugging sonar workflow. This should fail because of the parentheses `()` in the PR title.
> ci: Fix sonar's workflow parentheses() failing

- anta/tests/routing/bgp.py
- tests/units/anta_tests/routing/test_bgp.py
> fix(anta.tests): Fix VerifyBGPPeerMPCaps to handle missing capabilties

- anta/input_models/routing/ospf.py
- anta/tests/routing/ospf.py
- examples/tests.yaml
- tests/units/anta_tests/routing/test_ospf.py
> feat(anta.tests): Add VerifyOSPFSpecificNeighbors test

- anta/constants.py
- anta/reporter/md_reporter.py
- tests/data/test_md_report_extra_data.md
Added a new Markdown TOC including Run Overview when this section is generated.
> fix(anta): Add Run Overview to Markdown TOC

- anta/tests/interfaces.py
- examples/tests.yaml
- tests/units/anta_tests/test_interfaces.py
- tests/units/input_models/test_interfaces.py
Added new testcase VerifytOpticRxLevel to validate optic rx level
Added testcase - interfaces_optic_rx_test.py
> feat(anta.tests): Added new test case VerifyInterfacesOpticalReceivePower to validate optics receive power

- anta/tests/interfaces.py
- examples/tests.yaml
- tests/units/anta_tests/test_interfaces.py
Enhanced VerifyInterfacesTridentCounters inputs
Fixes #1255
> feat(anta.tests): Enhanced VerifyInterfacesTridentCounters inputs

- anta/tests/interfaces.py
- examples/tests.yaml
- tests/units/anta_tests/test_interfaces.py
- tests/units/input_models/test_interfaces.py
Minor fixes for recently merged PRs in main.
> fix(anta.tests): Minor fixes in the interfaces module

- anta/tests/hardware.py
- examples/tests.yaml
- tests/units/anta_tests/test_hardware.py
Added test to verify missing linecards
Fixes # https://github.com/aristanetworks/avd-internal/issues/254
> feat(anta.tests): Added test to verify missing linecards

- anta/constants.py
- anta/tests/hardware.py
- examples/tests.yaml
- tests/units/anta_tests/test_hardware.py
Added test VerifySandHealth to verify the sand (jericho) health
Fixes #https://github.com/aristanetworks/avd-internal/issues/254
Added testcases: system_hardware_sand_health_test.py
> feat(anta.tests): Added test VerifyChassisHealth

- anta/constants.py
- anta/tests/system.py
- examples/tests.yaml
- tests/units/anta_tests/test_system.py
> feat(anta.tests): Added test case to verify file presence

- anta/tests/hardware.py
- examples/tests.yaml
- tests/units/anta_tests/test_hardware.py
Added test VerifyHardwareCapacityUtilization to verifies hardware capacity utilization
Fixes #
> feat(anta.tests): Added test VerifyHardwareCapacityUtilization to verify hardware capacity utilization

- .pre-commit-config.yaml
- docs/scripts/generate_examples_tests.py
Added pre commit hook to validate examples/tests.yaml
> feat(anta): Added pre commit hook to validate examples/tests.yaml
