anta/inventory/__init__.py
anta/inventory/models.py
docs/api/README.md
docs/api/inventory.exceptions.md
docs/api/inventory.md
docs/api/inventory.models.md
scripts/clear-counters.py
tests/units/inventory_test.py

- Check if devices are online using `multiprocessing` lib and set flag `is_online=True` per device
- Build session for devices with flag `is_online` set to True
- Expose with `get_inventory()` method
`is_online` flag is required since variables are not natively shared and the Server object cannot serialized as it contains an SSLS session.
- Update name for methods
- Code re-ordering
- clear-counters script updated with new APIs and with logging disabled

feat(inventory): Add multiprocessing for inventory discovery

---

.pre-commit-config.yaml
CONTRIBUTING.md
requirements-dev.txt

Add pre-commit hook to support pylint validation
```
❯ echo "import foobaz" > test.py && git add test.py
❯ pre-commit
pylint...................................................................Failed
- hook id: pylint
- exit code: 22
************* Module test
test.py:1:0: C0114: Missing module docstring (missing-module-docstring)
test.py:1:0: E0401: Unable to import 'foobaz' (import-error)
test.py:1:0: W0611: Unused import foobaz (unused-import)
```
```
❯ pre-commit install
❯ pre-commit -h
usage: pre-commit [-h] [-V] {autoupdate,clean,gc,init-templatedir,install,install-hooks,migrate-config,run,sample-config,try-repo,uninstall,validate-config,validate-manifest,help,hook-impl} ...
positional arguments:
{autoupdate,clean,gc,init-templatedir,install,install-hooks,migrate-config,run,sample-confi …
```

make: add pre-commit hook for pylint

---

.gitignore
anta/inventory/__init__.py
anta/inventory/models.py
examples/inventory.yml

- Add new key in InventoryDevice to report HW type.
- Add mechanism to automatically discover HW type when building eAPI session
```python
class InventoryDevice(BaseModel):
"""Inventory model exposed by Inventory class."""
host: IPvAnyAddress
username: str
password: str
session: Any
established = False
is_online = False
hw_model: str = 'unset'
url: str
```

feat(inventory): Add HW discovery mechanism

---

anta/inventory/__init__.py

Make consistent output for get_inventory(). Now supports `native`, `list` or `json`
- `native`: An `InventoryDevices` objects
- `list`: A list of `InventoryDevice`
- `json`: A json string from `InventoryDevices`

fix(inventory): Use same output type for get_inventory in native format

---

anta/reporter/__init__.py
docs/usage.md

Add missing column to summary number of devices or tests skipped in aggregated
view.
```bash
$ python scripts/check-devices.py -i .personal/avd-lab.yml -c .personal/ceos-catalog.yml --table --by-test --test verify_mlag_status
Summary per test case
┏━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Test Case          ┃ # of success ┃ # of skipped ┃ # of failure ┃ # of errors ┃ List of failed or error nodes ┃
┡━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━╇━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ verify_mlag_status │ 8            │ 13           │ 0            │ 0           │ []                            │
└────────────────────┴──────────────┴──────────────┴──────────────┴─────────────┴─────────────── …
```

feat(anta.reporter): Add skipped column in aggregated results

---

README.md
anta/inventory/__init__.py
anta/inventory/models.py
scripts/check-devices.py

Implement issue #44 
- feat(inventory): Add initial support for tags
- doc: Fix typo in docstring
- Update inventory module to support tag filtering in get_inventory
- Update check-devices.py to support tags
Inventory example:
```yaml
anta_inventory:
hosts:
- host: 192.168.0.10
tags: ['test']
- host: 192.168.0.11
tags: ['dc1']
- host: 192.168.0.12
tags: ['dc1']
- host: 192.168.0.13
tags: ['dc2']
- host: 192.168.0.14
- host: 192.168.0.15
- host: 10.73.252.11
tags: ['dc1']
ranges:
- start: 10.73.252.12
end: 10.73.252.50
tags: ['clab']
```
Code execution
```bash
python scripts/check-devices.py -i .personal/avd-lab.yml -c .personal/ceos-catalog.yml --table --tags dc1
[08:07:43] INFO     Inventory .personal/avd-lab.yml loaded …
```

feat(inventory): Add tag support to filter test execution

---

anta/inventory/__init__.py
anta/inventory/models.py
anta/result_manager/__init__.py

Add docstring for tags option in different files

fix: Missing docstring for tags

---

.bumpversion.cfg
.gitignore
anta/__init__.py
requirements-dev.txt
setup.py

- Align `ANTA` versin to 0.3.0 to prepare next release
- Implement initial [`bump2version`](https://github.com/c4urself/bump2version) configuration
```bash
❯ bump2version patch --allow-dirty
0.2.1-dev
❯ bump2version release --allow-dirty
0.2.1-beta
❯ bump2version release --allow-dirty
0.2.1
```

make: Prepare version management

---

anta/result_manager/__init__.py
anta/tests/__init__.py

Fixing issue #128
- rename `testcase.host` by `testcase.name` in `get_hosts()` 
- rename `result.host` by `result.name` in`get_result_by_host()`

fix: Rename field in get_hosts() to match updated TestResult model

---

scripts/check-devices.py

Update default logging behaviour to not list all tests addition in result manager by default
- Configure `INFO` only for `check-devices.py` script
- Configure `WARNING` for `anta.inventory` module
- Configure `WARNING` for `anta.result_manager` module
To change logging for `anta.inventory` & `anta.result_manager`, `--loglevel` option can be used

feat(check-devices): Update default logging behavior

---

pyproject.toml

Fix an issue where submodules where not correctly installed when using `pip`.

fix: Add missing sub-module in pyproject

---

anta/tests/configuration.py
tests/units/test_tests/test_configuration.py

Allow to run `verify_running_config` whitout setting a fake enable password if not configured in CLI.

fix(anta.tests): Allow verify_running_config to support no enable pasword

---

anta/cli/exec/commands.py
anta/cli/exec/utils.py

- Modified `collect_commands()` logic to use `asyncio.gather()` instead of the synchronous logic with a for loop.
- The `--output-directory` option of the `anta exec snapshot` command could be None if not provided and created a folder with that name. Added a default value and a timestamp to avoid overriding previous command collections.

fix(anta.cli): Improve 'anta exec snapshot'

---

anta/tests/vxlan.py
tests/units/anta_tests/vxlan/data.py
tests/units/anta_tests/vxlan/test_exc.py

I made two adjustments to the test cases, as this seemed appropriate
1. If the `Vxlan1` interface can't be found, we mark it as a [`skip`](https://github.com/colinmacgiolla/network_tests_automation/blob/d170dcab3e7a66dd9a08eb22800bc1e17e81d92e/anta/tests/vxlan.py#L30) rather than a [`fail`](https://github.com/colinmacgiolla/network_tests_automation/blob/601962884e0284da22d7202cb300ba7d36ad9345/anta/tests/vxlan.py#L35)
2. I added the `platform_dependent` category to our [pass/fail set](https://github.com/colinmacgiolla/network_tests_automation/blob/d170dcab3e7a66dd9a08eb22800bc1e17e81d92e/anta/tests/vxlan.py#L63) since that seemed useful for older R/R2 series systems

refactor(anta.tests): Refactor VXLAN tests

---

.gitignore
anta/cli/exec/utils.py
anta/result_manager/models.py

Remove sending `{"cmd": "enable", "input": enable_pass}` if enable_password is not required in user's setup.
Fixes #208

fix(anta.cli): Update exec snapshot to support no enable-password

---

anta/cli/check/commands.py
anta/cli/check/utils.py
anta/cli/cli.py
anta/reporter/__init__.py
anta/result_manager/__init__.py
docs/cli/nrfu.md
pyproject.toml

Implement option to render result using jinja2 template so it can be fully customised by the user.
```bash
anta nrfu tpl-report -c .personal/catalog-class.yml -tpl .personal/test_template.j2 -o .personal/demo.txt
╭───────────────────────── Settings ─────────────────────────╮
│ Running check-devices with:                                │
│               - Inventory: .personal/inventory_atd.yml     │
│               - Tests catalog: .personal/catalog-class.yml │
│               - Template: .personal/test_template.j2       │
╰────────────────────────────────────────────────────────────╯
* verify_zerotouch is SUCCESS for spine01
* verify_running_config_diffs is SUCCESS for spine01
* verify_interface_utilization is SUCCESS for spine01
❯ cat .personal/demo.txt
* verify_zerotouch is …
```

feat(anta): Implement Result manager for Jinja2 rendering

---

anta/cli/check/commands.py
anta/cli/utils.py
anta/runner.py
docs/usage-inventory-catalog.md

Fixes #212 
Changes:
- feat(anta): Enable support for AntaTestTemplate
- fix(anta.cli): propagate setup_logging to all nrfu CLI
New Catalog option for AntaTestTemplate based test
```yml
anta.tests.routing.bgp:
- VerifyBGPIPv4UnicastCount:
number: 3 
tpl_options:
- vrf: default
```

feat(anta): Enable support for AntaTestTemplate

---

anta/models.py
anta/tests/aaa.py
anta/tests/configuration.py
anta/tests/interfaces.py
anta/tests/logging.py
anta/tests/mlag.py
anta/tests/security.py
anta/tests/snmp.py
anta/tests/vxlan.py

Removed `self.logger` in `AntaTest` class as per the Python recommendation: https://docs.python.org/3/library/logging.html#logger-objects
The logger name hierarchy is analogous to the Python package hierarchy, and identical to it if you organise your loggers on a per-module basis using the recommended construction logging.getLogger(__name__). That’s because in a module, __name__ is the module’s name in the Python package namespace.
This would also avoid having things logged as `anta.models` when the actual code is somewhere in `anta.tests`.
I also removed the static `setLevel` calls. I did not get how I am supposed to change the logging level with the `--log-level` CLI option if some modules are always using `ERROR` or `CRITICAL`

fix(anta): fix logging

---

anta/cli/check/commands.py
anta/cli/check/utils.py
anta/cli/cli.py
anta/cli/debug/commands.py
anta/cli/exec/commands.py
anta/cli/exec/utils.py
anta/cli/get/commands.py
anta/cli/utils.py
anta/inventory/__init__.py
anta/inventory/models.py
anta/loader.py
anta/models.py
anta/result_manager/__init__.py
anta/runner.py
anta/tools/pydantic.py
docs/advanced_usages/as-python-lib.md
tests/data/json_data.py
tests/units/inventory/test_inventory.py
tests/units/inventory/test_models.py

This PR brings the following main changes:
- Do not use pydantic for AntaDevice class anymore
- Introduce optional coroutine copy() for AntaDevice
- Refactor CLI scripts to use Click callbacks

refactor(anta): Refactor AntaDevice and CLI scripts

---

anta/reporter/__init__.py

Implement 2 new columns in NRFU report for test description and test categories
```bash
All tests results
┏━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Device IP ┃ Test Name                  ┃ Test Status ┃ Message(s) ┃ Test description                              ┃ Test category ┃
┡━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ spine01   │ VerifyZeroTouch            │ success     │            │ Verifies ZeroTouch is disabled.               │ configuration │
│ spine01   │ VerifyRunningConfigDiffs   │ success     │            │                                               │ configuration │
│ spine01   │ …
```

feat(anta): Add test categories and description to nrfu report

---

.pre-commit-config.yaml
anta/cli/exec/utils.py
anta/cli/nrfu/commands.py
anta/cli/nrfu/utils.py
anta/decorators.py
anta/inventory/__init__.py
anta/models.py
anta/runner.py
pylintrc

Fixes #244 
https://asciinema.org/a/YabNWrcJOBHhMOoyjxtS3R64w

feat(anta.cli): Add Progress Bar for NRFU

---

anta/cli/__init__.py
anta/cli/utils.py

* NOTE - this may impact performance so maybe needs to be reassessed
Fixes #263

feat: Allow --help for subcommands

---

anta/tests/vxlan.py
docs/api/tests.md
docs/api/tests.vxlan.md
examples/tests.yaml
mkdocs.yml
tests/units/anta_tests/vxlan/data.py
tests/units/anta_tests/vxlan/test_exc.py

* rename `VerifyVxlan` to `VerifyVxlanInterface`
* update documentation

feat(anta.tests)!: Update VXLAN tests

---

anta/cli/__init__.py
anta/cli/get/commands.py
anta/cli/get/utils.py
docs/cli/inv-from-ansible.md
mkdocs.yml

Add a new command to create ANTA inventory from an Ansible inventory file:
```
anta get from-ansible --help
Usage: anta get from-ansible [OPTIONS]
Build ANTA inventory from an ansible inventory YAML file
Options:
-g, --ansible-group TEXT        Ansible group to filter
-i, --ansible-inventory FILENAME
Path to your ansible inventory file to read
-o, --output FILENAME           Path to save inventory file
-d, --inventory-directory PATH  Directory to save inventory file
--help                          Show this message and exit.
```
```
anta get from-ansible -i .personal/ansible-avd-inv.yml -d .personal -o demo.yml -g tooling
* adding entry for {'name': 'srv-pod01', 'host': '10.73.252.41'}
* adding entry for {'name': 'srv-pod02', 'host': '10.73.252.42'}
* adding entry for {'name': …
```

feat(anta.cli): Add support for creating ANTA inventory from Ansible

---

anta/device.py
tests/units/test_device.py

fix(anta): AsyncEOSDevice.name does not contain None if port is not set

---

anta/tests/hardware.py
tests/units/anta_tests/hardware/data.py
tests/units/anta_tests/hardware/test_exc.py

`VerifyEnvironmentPower` and `VerifyEnvironmentCooling` tests are now skipped if the accepted_states list if not provided.
This will force users to specify the accepted_states. Will be used in AVD.

feat(anta.tests)!: Update Hardware tests

---

anta/cli/exec/utils.py

Fix an issue where `anta exec snapshot` crashed when all format keys are not
defined in YAML file.
Fixes #268

fix(anta.cli): Allow list of commands to not have all supported format defined

---

.github/workflows/code-testing.yml
anta_inventory/inventory-custom_container.yml
anta_inventory/inventory.yml
custom/inventory.yml

Implement job selector based on 2 options:
- code: everything in `anta/` and `tests/`
- doc: everything based on `docs`, `README.md` and `mkdocs.yml`

ci: implement job-selector to speed up CI

---

:wq
anta/cli/exec/commands.py
tests/units/cli/exec/test_commands.py

Remove timestamp when user provide a custom folder name with `-o` or env
variable
Timestamp remains for default output folder.
Fixes #271

fix(anta.cli): Remove timestamp from custom output folder in exec snapshot

---

anta/cli/exec/utils.py
docs/cli/exec.md

Using `show running-config | include aaa authorization exec default local` to check for required AAA config for SCP is too restrictive.
Use `show running-config | include aaa authorization exec default` instead.

fix: aaa configuration check in `anta exec collect-tech-support`

---

anta/device.py

Get inventory update:
```
❯ anta get inventory
Current inventory content is:
{
'spine01': AsyncEOSDevice(
name='spine01',
tags=['fabric', 'spine', 'all'],
hw_model=None,
is_online=False,
established=False,
host='192.168.0.10',
eapi_port=443,
username='ansible',
enable=False,
insecure=False
)
}
```
Passwords have been hidden in data structures shown in ANTA DEBUG mode:
```
ANTA_DEBUG=true anta get inventory
{
'spine1': AsyncEOSDevice(
name='spine1',
tags=['clab', 'spine', 'all'],
hw_model=None,
is_online=False,
established=False,
host='clab-evpn-vxlan-fabric-spine1',
eapi_port=443,
username='admin',
enable=True,
insecure=True,
_session={
'port': 443,
'host': 'clab-evpn-vxlan-fabric-spine1',
'auth': <httpx.BasicAuth object at 0x7fcb10fcba30>,
'_base_url': …
```

fix(anta): Remove paswsord field in get inventory and debug

---

anta/cli/__init__.py
anta/cli/utils.py
docs/README.md
docs/snippets/anta_help.txt

Use click [password_option](https://click.palletsprojects.com/en/8.1.x/api/#click.password_option) and [prompt](https://click.palletsprojects.com/en/8.1.x/api/#click.prompt) to prompt EOS passwords if not provided via environment variables or CLI options.
This is to provide a more secure way to provide passwords without using environment variables.

feat: prompt passwords from stdin if not provided via CLI options

---

anta/tests/logging.py
anta/tests/system.py
examples/tests.yaml
tests/units/anta_tests/logging/data.py
tests/units/anta_tests/logging/test_exc.py
tests/units/anta_tests/system/data.py
tests/units/anta_tests/system/test_exc.py

Move anta.tests.system.VerifySyslog test to anta.tests.logging.VerifyLoggingErrors.
For now, the test has been modified to verify syslog messages with a severity of ERRORS or higher instead of WARNING.
The last 7 days has been removed as well to optimize test performance on devices with large log buffers.
This test can be revisited in the future once we implement caching in #342.
Fixes: #332

fix(anta.tests)!: Update VerifySyslog

---

anta/cli/__init__.py
anta/cli/utils.py

Add support for auto aliases in CLI to detect commands with CLI shortcut
So user can type short string instead of full keywords until they are unique.
Below is an example
> **warning**
> It is not applicable to options and arguments
```bash
❯ anta nrfu -c .personal/catalog-class.yml table --group-by device
❯ anta nr -c .personal/catalog-class.yml tab --group-by device
╭────────────────────── Settings ──────────────────────╮
│ Running ANTA tests:                                  │
│ - ANTA Inventory contains 6 devices (AsyncEOSDevice) │
│ - Tests catalog contains 4 tests                     │
╰──────────────────────────────────────────────────────╯
```

feat(anta.cli): Enable CLI command auto aliases

---

tests/conftest.py

Fixes #385 
Because of the voodoo magic from @mtache  we need to tell pytest to rewrite the asserts on `tests.lib.anta` when it is imported.
Tested manually:
* modify one test to make it fail - check that the assertion message is comprehensive
* comment the line in conftest and run again - check that you get only `Assertion Error`

chore: Add rewrite back to generic test

---

anta/models.py
docs/api/models.md
tests/units/test_models.py

Add support of a list of blacklisted regex to secure test execution and avoid
any critical change on devices.
It currently blocked CLI with following regex
- Reload command: `^reload\s*\w*`
- Configure mode: `^conf\w*\s*(terminal|session)*`
- Write: `^wr\w*\s*\w+`
Fixes #413

feat(anta): Add support for command blacklist to secure tests

---

anta/tests/connectivity.py
tests/units/anta_tests/test_connectivity.py

Added a check in `VerifyLLDPNeighbors` when the interface is not configured on the device. The test will now fail and give a proper message instead of generating a `KeyError`.

fix(anta.tests): Fix VerifyLLDPNeighbors

---

anta/custom_types.py
anta/tests/vxlan.py
examples/tests.yaml
tests/units/anta_tests/test_vxlan.py

New VXLAN tests:
- VerifyVxlanVniBinding
- VerifyVxlanVtep

feat(anta.tests): New VXLAN tests

---

docs/contribution.md
docs/requirements-and-installation.md
pyproject.toml

* feat(anta.tests): New VXLAN tests by @carl-baillargeon in https://github.com/arista-netdevops-community/anta/pull/431
* feat(anta): Add tag mapping between devices and tests by @titom73 in https://github.com/arista-netdevops-community/anta/pull/377
* feat(anta.cli): Check catalog functionality by @gmuloc in https://github.com/arista-netdevops-community/anta/pull/414
* fix(anta.tests): Fix VerifyLLDPNeighbors by @carl-baillargeon in https://github.com/arista-netdevops-community/anta/pull/430
* fix(anta.tests): Fix VerifyVxlanVtep result failure messages by @carl-baillargeon in https://github.com/arista-netdevops-community/anta/pull/433
* fix: improve error handling and ansible group parsing of anta get from-ansible by @mtache in https://github.com/arista-netdevops-community/anta/pull/449 …

bump: Version 0.10.0 -> 0.11.0

---

anta/catalog.py
tests/data/test_catalog_wrong_type.yml
tests/units/test_catalog.py

More Guards
Fixes #457 
Fixes #460

fix(anta): Catalog issues when parsed data has the wrong type

---

anta/cli/get/commands.py
docs/cli/inv-from-ansible.md
tests/units/cli/get/test_commands.py

Use configured anta inventory if `--output` is not configured in `anta get from-ansible` command.
```bash
anta get from-ansible --ansible-inventory ../anta-lab/atd-inventory/inventory.yml
[19:02:09] INFO     Building inventory from ansible file ../anta-lab/atd-inventory/inventory.yml
[19:02:12] INFO     output anta inventory is: anta-lab/network-tests/inventory.yml
INFO        * adding entry for cv_atd1
INFO        * adding entry for spine1
INFO        * adding entry for spine2
INFO        * adding entry for leaf1 
INFO        * adding entry for leaf2 
INFO        * adding entry for leaf3
INFO        * adding entry for leaf4
INFO     ANTA device inventory file has been created in anta-lab/network-tests/inventory.yml
```
If destination file has content, then cli asks confirmation to user …

fix(anta.cli): Use configured anta inventory as output by default in get from-ansible

---

anta/cli/get/commands.py
docs/cli/inv-from-ansible.md

Remove a confusing option (`-i`) from the cli under `anta get from-ansible`
```
anta get from-ansible --help
Usage: anta get from-ansible [OPTIONS]
Build ANTA inventory from an ansible inventory YAML file
Options:
-g, --ansible-group TEXT        Ansible group to filter
--ansible-inventory FILENAME
Path to your ansible inventory file to read
-o, --output FILENAME           Path to save inventory file
-d, --inventory-directory PATH  Directory to save inventory file
--help                          Show this message and exit.
```

fix(anta.cli)!: Remove confusing -i option in anta get from-ansible

---

docs/advanced_usages/custom-tests.md
docs/api/tests.routing.bgp.md

doc: Remove BGP deprecated doc

---

mkdocs.yml

Missa made a bad mkdocs / mike setting and this somehow caught up

doc: Banner for main being unstable is hidden because of this setting

---

docs/contribution.md
docs/requirements-and-installation.md
pyproject.toml

* fix(anta.cli)!: Remove confusing -i option in anta get from-ansible by @titom73 in https://github.com/arista-netdevops-community/anta/pull/474
* fix(anta.cli)!: Avoid requiring username, password, inventory for the get commands by @gmuloc in https://github.com/arista-netdevops-community/anta/pull/447
* feat(anta.cli): Show lines between table rows for readability by @paullavelle in https://github.com/arista-netdevops-community/anta/pull/455
* feat: unsupported platform warning by @mtache in https://github.com/arista-netdevops-community/anta/pull/437
* feat: Custom type Interface will format interface name by @mtache in https://github.com/arista-netdevops-community/anta/pull/480
* fix(anta): Catalog issues when parsed data has the wrong type by @gmuloc in …

bump: ANTA v0.12.0

---

anta/tools/get_item.py
tests/units/tools/test_get_item.py

Add `get_item` function to help with tests.

feat(anta): Add get_item function

---

anta/tests/routing/bgp.py
examples/tests.yaml
tests/units/anta_tests/routing/test_bgp.py

Add the test case to verify the BGP neighbor routes 
Run the testcase by adding catalog as below:
```
anta.tests.routing:
bgp:
- VerifyBGPExchangedRoutes:
bgp_peers:
- peer_address: 172.30.255.5
vrf: default
advertised_routes:
- 192.0.254.5/32
received_routes:
- 192.0.255.4/32
- peer_address: 172.30.255.1
vrf: default
advertised_routes:
- 192.0.255.1/32
- 192.0.254.5/32
received_routes:
- 192.0.254.3/32
```
1. Testcase pass when routes are correct:
```
All tests results                                                                                           
┏━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Device    ┃ Test Name …
```

feat(anta.tests)!: Adding the test case to verify BGP neighbor routes

---

anta/tests/security.py
examples/tests.yaml
tests/units/anta_tests/test_security.py

Added testcase to verify Login and Motd banner.
Fixes #524

feat(anta.tests): Added testcase to verify Login and Motd banner

---

anta/tests/connectivity.py
anta/tests/hardware.py
anta/tests/interfaces.py
anta/tests/mlag.py
anta/tests/routing/bgp.py
anta/tests/routing/generic.py
anta/tests/routing/ospf.py
anta/tests/security.py
anta/tests/system.py
anta/tests/vxlan.py

Clean test descriptions, categories and docstrings. More concise.

fix(anta.tests): Clean test descriptions, categories and docstrings

---

anta/tests/greent.py
anta/tests/lanz.py
anta/tests/ptp.py
tests/units/anta_tests/test_greent.py
tests/units/anta_tests/test_lanz.py
tests/units/anta_tests/test_ptp.py

Add new tests for LANZ , GreenT and PTP.

feat(anta.tests): Add LANZ, PTP and GreenT

---

anta/result_manager/__init__.py
tests/lib/fixture.py
tests/units/result_manager/test__init__.py

`get_json_results` function in `ResultManager` was serializing `None` objects to `'None'` instead of `null`.
It will now use the built-in `model_dump` from Pydantic for proper serialization.

fix(anta): get_json_results returns null instead of "None"

---

anta/cli/exec/utils.py

Add protection to allow user to snapshot a command that use invalid character for filename. If an invalid character is found in filename, it is replaced by `_` character.

fix(anta.cli): Allow commands in snapshot to use / and protect filename

---

anta/custom_types.py
anta/tests/mlag.py
examples/tests.yaml
tests/units/anta_tests/test_mlag.py

Added testcase for MLAG primary priority
Fixes #529 
Success: The test will pass if the MLAG state is set as 'primary' and the priority matches the input.
Failure: The test will fail if the MLAG state is not 'primary' or the priority doesn't match the input.
Skipped: The test will be skipped if MLAG is 'disabled'.

feat(anta.tests): Added testcase for MLAG primary priority

---

anta/tests/routing/bgp.py
examples/tests.yaml
pyproject.toml
tests/units/anta_tests/routing/test_bgp.py

This test verifies the EVPN Type-2 routes for a given IPv4 or MAC address and VNI.
* success: If all provided VXLAN endpoints have at least one valid and active path to their EVPN Type-2 routes.
* failure: If any of the provided VXLAN endpoints do not have at least one valid and active path to their EVPN Type-2 routes.
- Added new test
- Cleanup old BGP function
- Added new pydantic_extra_types to requirements

feat(anta.tests): New BGP EVPN Type-2 route test

---

anta/tests/routing/bgp.py
examples/tests.yaml
tests/units/anta_tests/routing/test_bgp.py

Adding the test case to verify BGP timers
Fixes #509

feat(anta.tests): Adding the test case to verify BGP timers

---

anta/custom_types.py
anta/tests/vxlan.py
examples/tests.yaml
tests/units/anta_tests/test_vxlan.py

Added testcase to verify vxlan1 source interface and udp port.
Fixes #553 
Verifies the VXLAN source interface and UDP port.
* success: Passes if VXLAN source interface and UDP port are correct.
* failure: Fails if VXLAN source interface or UDP port are incorrect.
* skipped: Skips if the Vxlan1 interface is not configured.

feat(anta.tests): Added testcase to verify vxlan1 source interface and udp port

---

anta/tests/bfd.py
anta/tests/routing/generic.py
docs/api/tests.bfd.md
docs/api/tests.md
examples/tests.yaml
mkdocs.yml
tests/units/anta_tests/routing/test_generic.py
tests/units/anta_tests/test_bfd.py

1. Moved VerifyBFD testcase from generic to bfd file and rename with VerifyBFDPeersHealth
2. Added the remote dick verification and an optional input parameter of last down to verify if peer was down more threshold hours.
Fixes #503

refactor(anta.tests)!: Update the pass/fail criteria for testcase VerifyBFD

---

anta/custom_types.py
anta/tests/services.py
examples/tests.yaml
tests/units/anta_tests/test_services.py

Added testcase to verify errordisable recovery reason.
```
Verifies the error-disable recovery reason, status, and interval.
* Success: The test will pass if the error-disable recovery reason status is enabled and the interval matches the input.
* Failure: The test will fail if the error-disable recovery reason is not found, the status is not enabled, or the interval does not match the input.
```
Fixes #538

feat(anta.tests): Added testcase to verify errordisable recovery reason

---

anta/tests/security.py
examples/tests.yaml
tests/units/anta_tests/test_security.py

Added testcase to verify IPv4 ACL sequence entries. 
Note: This test only check if a acl is configured and input entries sequence are same in actual output. It will not fail if we have 2 entries of a acl in input but in actual output there are more then 2 entries. If input two entries sequence is match with actual output then testcase will pass. @carl-baillargeon 
```
Expected results:
* success: The test will pass if an IPv4 ACL is configured with the correct sequence entries.
* failure: The test will fail if an IPv4 ACL is not configured or entries are not in sequence.
```
Fixes #543

feat(anta.tests): Added testcase to verify IPv4 ACL sequence entries

---

anta/tests/interfaces.py
examples/tests.yaml
tests/units/anta_tests/test_interfaces.py

Added testcase to verify ip address(primary and secondary) on interface.
Fixes #545 
* success: The test will pass if an interface is configured with a correct primary and secondary IPv4 address.
* failure: The test will fail if an interface is not found or the primary and secondary IPv4 addresses do not match with the input.
Note: There is no optional input. All the input is required and restricted with values.

feat(anta.tests): Added testcase to verify ip address on interface

---

anta/tests/interfaces.py
examples/tests.yaml
tests/units/anta_tests/test_interfaces.py

Added testcase to verify IP virtual router mac  address
"""
Verifies the IP virtual router MAC address.
* success: The test will pass if the IP virtual router MAC address matches the input.
* failure: The test will fail if the IP virtual router MAC address does not match the input.
"""
Fixes #561

fix(anta.tests): Added testcase to verify IP virtual router mac  address

---

anta/tests/interfaces.py
examples/tests.yaml
tests/units/anta_tests/test_interfaces.py

Fix VerifyInterfacesStatus to support more options for line protocol status.

fix(anta.tests): Fix VerifyInterfacesStatus to support more options for line protocol status

---

anta/tests/interfaces.py
tests/units/anta_tests/test_interfaces.py

Fix an issue where interface name like `Ethernet1/1` or `Port-Channel1` were not caught by the test reporting `VerifyL2MTU`

fix(anta.tests): Fix an issue in VerifyL2MTU to capture interface name

---

anta/tests/field_notices.py
anta/tests/hardware.py
anta/tests/lanz.py
anta/tests/profiles.py
anta/tests/ptp.py

Added 'cEOSCloudLab' in skip decorator.
Fixes #560 
1. VerifyFieldNotice44Resolution: Command(`show version detail`) is supported but its verify Aboot version per FN0044 which is not needed for cEOSCloudLab.
2. VerifyFieldNotice72Resolution: Command(`show version detail`) is supported but its verify the device is exposed to FN0072, and if the issue has been mitigated which is not needed for cEOSCloudLab.
3. VerifyTransceiversManufacturers: No xcvrSlots for cEOSCloudLab device.
4. VerifyTemperature: No need to check temp for cEOSCloudLab device.
5. VerifyTransceiversTemperature: No need to check temp for cEOSCloudLab device.
6. VerifyEnvironmentSystemCooling: No need to check cooling for cEOSCloudLab device.
7. VerifyEnvironmentCooling: No need to check cooling of power and fan slots for …

fix(anta.tests): Added 'cEOSCloudLab' in skip decorator

---

docs/advanced_usages/custom-tests.md
mkdocs.yml

doc(anta.tests): Update custom-tests.md to reflect the new test docstring format

---

anta/tests/routing/ospf.py
examples/tests.yaml
tests/units/anta_tests/routing/test_ospf.py

This PR introduces a new feature for anta OSPF test:
Verifies LSAs present in the OSPF link state database did not cross the maximum LSA Threshold
* Success: The test will pass if all OSPF instances did not cross the maximum LSA Threshold.
* Failure: The test will fail if some OSPF instances crossed the maximum LSA Threshold.
* Skipped: The test will be skipped if no OSPF instance is found.

feat(anta.tests): Add OSPF Max LSA Test

---

anta/tests/aaa.py
anta/tests/bfd.py
anta/tests/configuration.py
anta/tests/connectivity.py
anta/tests/field_notices.py
anta/tests/greent.py
anta/tests/hardware.py
anta/tests/interfaces.py
anta/tests/lanz.py
anta/tests/logging.py
anta/tests/mlag.py
anta/tests/multicast.py
anta/tests/profiles.py
anta/tests/ptp.py
anta/tests/routing/bgp.py
anta/tests/routing/generic.py
anta/tests/routing/ospf.py
anta/tests/security.py
anta/tests/services.py
anta/tests/snmp.py
anta/tests/software.py
anta/tests/stp.py
anta/tests/system.py
anta/tests/vlan.py
anta/tests/vxlan.py
docs/advanced_usages/as-python-lib.md
docs/advanced_usages/custom-tests.md

fix(anta.tests): Add latest eAPI command revision number to all tests

---

pyproject.toml
tests/units/anta_tests/test_field_notices.py
tests/units/test_models.py

Fixed the Ruff formatting for below files:
tests/units/anta_tests/test_field_notices.py
tests/units/test_models.py
Fixes #613

refactor(anta): Fix the Ruff formatting and run ruff formatting in CI

---

anta/cli/get/commands.py
anta/cli/get/utils.py
docs/cli/inv-from-ansible.md
tests/data/ansible_inventory_with_vault.yml
tests/units/cli/get/test_utils.py

Maintainer decision was to not support Ansible inline vaulted variables.
This PR captures the exception properly, emit a nice error message and add documentation on this topic.
Fixes #630

refactor(anta): Emit log message when failing on Ansible vault variable

---

.pre-commit-config.yaml
pyproject.toml

* sort dep in pyproject
Current pre-commit hook was failing with Python3.12 because of Pyyaml 6.0.0 hardcoded (https://github.com/yaml/pyyaml/issues/756)

ci: Update pre-commit mypy additional dependencies

---

anta/catalog.py
anta/logger.py
anta/models.py
anta/runner.py
anta/tools.py
pyproject.toml
tests/units/test_catalog.py
tests/units/test_runner.py

Refactor ANTA runner to use indexes for tags for faster execution. Also moved some of the logic outside of the main function for clarity and manageability.
Updated unit tests.

fix(anta): Optimize device to tests creation in ANTA runner

---

anta/tests/routing/isis.py
docs/api/tests.routing.isis.md
examples/tests.yaml
mkdocs.yml
tests/units/anta_tests/routing/test_isis.py

Implement new set of tests to cover IS-IS and Segment Routing
Related to #636

feat(anta.tests): Add IS-IS tests collection

---

docs/stylesheets/extra.material.css
mkdocs.yml

Update CSS to make H3,H4,H5 and H6 title bit more readable with more emphasis
To test:
```bash
mkdocs serve
```

doc(anta): Update CSS for better titles readability

---

anta/cli/exec/utils.py
anta/tests/field_notices.py
anta/tests/interfaces.py
anta/tests/routing/bgp.py
anta/tests/stp.py
docs/scripts/generate_svg.py
tests/units/anta_tests/routing/test_bgp.py
tests/units/anta_tests/test_field_notices.py
tests/units/anta_tests/test_interfaces.py

* Rollback some modifications because commands are not created in the same order than the inputs.
* Fix pylint 3.2.0 new warnings 
Fixes #669

fix(anta.tests): Correct inputs to outputs mapping for BGP tests

---

anta/tests/avt.py
anta/tests/path_selection.py

fix(anta.tests): Fix AVT and Path-Selection tests to be skipped on cEOSlab and vEOS-lab

---

Dockerfile
anta/cli/exec/utils.py
anta/custom_types.py
anta/models.py
tests/units/test_custom_types.py

Approach to support regular expression unit test. So it is easier to change a regexp and check if it is not broken.

refactor: Extract regular expression to support regexp unit tests

---

anta/cli/get/commands.py
anta/cli/get/utils.py
anta/inventory/models.py
docs/cli/inv-from-cvp.md
tests/units/cli/get/test_commands.py
tests/units/cli/get/test_utils.py

Fix sonarcloud issue and another found issue when rendering the inventory.
Fixes #699

feat(anta.cli): Make CV certs verified by default

---

.github/workflows/secret-scanner.yml

Switch to the secret scanner workflow that works for public repos.

ci: Public repo secret scanner

---

.github/workflows/secret-scanner.yml

Use public action to run secret scanner. Pulling and running docker image directly makes it hard for the secret scanner team to make changes in the future.

ci: Update secret-scanner to use public action

---

anta/cli/nrfu/__init__.py
anta/cli/nrfu/commands.py
anta/cli/nrfu/utils.py

Today `anta nrfu tpl-report` runs the test and then raise when it realises that the template file is missing
Thats not what is intended
Fixes field reported issue

fix(anta.cli): Evaluate nrfu subcommands args before running the tests

---

anta/catalog.py
anta/cli/nrfu/__init__.py
anta/cli/utils.py
docs/cli/check.md
docs/snippets/anta_nrfu_help.txt
docs/usage-inventory-catalog.md
tests/data/test_catalog.json
tests/data/test_catalog_invalid_json.json
tests/units/cli/nrfu/test__init__.py
tests/units/test_catalog.py

Add support for JSON format for catalogs
Fixes #714

feat(anta): Add support for JSON catalogs

---

anta/cli/nrfu/__init__.py
docs/snippets/anta_nrfu_help.txt

fix(anta.cli): Update --hide description under anta nrfu

---

examples/README.md
examples/tests.yaml

fix: Add missing testcases in example folder

---

.pre-commit-config.yaml
anta/models.py
anta/tests/routing/bgp.py
asynceapi/device.py
asynceapi/errors.py
pyproject.toml

cryptography 43.0.0 generate warnings and we run pytest with transforming warning into erros.
Opened this: https://github.com/ronf/asyncssh/issues/674 but in the meantime accepting the warning in our CI

ci: Ignore cryptography>43.0.0 warnings

---

anta/tests/connectivity.py
examples/tests.yaml
tests/units/anta_tests/test_connectivity.py

- Updated the test case to include optional field of DF bit(Updated input model for df-bit) in command.
- Included optional field of packet size variation(Updated input model for packet size) in command.
Fixes #756

feat(anta): Refactor VerifyReachability test case to add coverage for DF Bit, packet size

---

anta/tests/routing/generic.py
tests/units/anta_tests/routing/test_generic.py

Reduce number of commands executed on VerifyRoutingTableEntry by querying all routes of a vrf in one go.

feat(anta.tests): Optimize VerifyRoutingTableEntry by quering all routes for a vrf.

---

anta/custom_types.py
anta/tests/routing/bgp.py
examples/tests.yaml
tests/units/anta_tests/routing/test_bgp.py

This test case checks if specified BGP drop statistics are zero, ensuring that no BGP messages
are being dropped.(Inbound updates, Inbound paths, Outbound paths).
* Success: The test will pass if the BGP peer's drop statistics are zero.
* Failure: The test will fail if the BGP peer's drop statistics are non-zero.
Fixes #769

feat(anta): Added the test case to verify Inbound/outbound stats for BGP neighbors

---

pyproject.toml

Griffe v1 was released so we need to put an upper bound on Griffe requirement until we update the code to support v1.
https://github.com/mkdocstrings/griffe/releases/tag/0.46.0

fix(anta): Add upper bound on Griffe requirement for v1

---

anta/custom_types.py
anta/tests/bfd.py
examples/tests.yaml
tests/units/anta_tests/test_bfd.py

All neighbor IPs where PEER_GROUP has BFD_ENABLED=true should be displayed with respective registered protocol(i.e ISIS or BGP etc)
**Note: Added revision fix in VerifyBFDPeersIntervals, VerifyBFDSpecificPeers revision 1 as later revision introduces additional nesting for type**
Fixes #766

feat(anta): Added test case to verify registered protocol for IPv4 BFD peers

---

anta/catalog.py
docs/usage-inventory-catalog.md
tests/units/test_catalog.py

- Added `merge_catalogs` function to the `catalog.py` module.
- Updated `AntaCatalog.merge` to use that function.
Fixes #715

feat(anta): Added merge_catalogs function

---

anta/cli/nrfu/commands.py
anta/cli/nrfu/utils.py
docs/cli/nrfu.md
tests/units/cli/nrfu/test_commands.py

When using the CLI command `anta nrfu json --output ./results.json`, results will be saved in a JSON file without printing to the console.
Fixes #760

fix(anta): Remove JSON output when saving to a file

---

anta/tests/bfd.py
tests/units/anta_tests/test_bfd.py

In eAPI reports the interval timers are in microseconds instead of milliseconds so converted timers in to milliseconds to be consistent with the inputs.
Fixes #799

feat(anta): Updated VerifyBFDPeersIntervals for failure message to be in milliseconds like the inputs

---

anta/tests/system.py
examples/tests.yaml
tests/units/anta_tests/test_system.py

NTP associations for all NTP servers should be up as denoted by the "condition" field below, and the primary NTP server should be preferred.
primary server will have condition "sys.peer", and pri server is denoted using "preferred: true "
other servers will have condition "candidate"
Fixes #753

feat(anta): Added the test case to verify NTP associations functionality

---

.github/workflows/code-testing.yml
.pre-commit-config.yaml
anta/catalog.py
anta/custom_types.py
anta/tests/field_notices.py
anta/tests/interfaces.py
anta/tests/mlag.py
anta/tests/routing/bgp.py
anta/tests/routing/generic.py
anta/tests/security.py
anta/tests/system.py
pyproject.toml
tests/benchmark/__init__.py
tests/benchmark/conftest.py
tests/benchmark/test_anta.py
tests/benchmark/utils.py
tests/units/anta_tests/routing/test_generic.py
tests/units/anta_tests/test_configuration.py
tests/units/anta_tests/test_field_notices.py
tests/units/anta_tests/test_interfaces.py
tests/units/anta_tests/test_mlag.py
tests/units/anta_tests/test_security.py
tests/units/anta_tests/test_system.py
tests/units/test_custom_types.py

Use [Codspeed](https://codspeed.io/) to benchmark ANTA.
Use [RESPX](https://lundberg.github.io/respx/) to mock eAPI responses.
The code generates an ANTA catalog from the unit test data at [tests/units/anta_tests](https://github.com/aristanetworks/anta/tree/main/tests/units/anta_tests).
We should consider refactoring these data to use a dictionary with a tuple (Type[AntaTest], [unit test name]: str) as key to avoid duplicates.
It relies on a specific eAPI request ID format: `ANTA-{test name}:{unit test name}:{command index}-{command UUID}`. We currently patch ANTA commands to implement this, but we could consider implementing this directly in ANTA (the eAPI request ID is used for debugging purpose and its format has been arbitrary set to `ANTA-{test name}-{command UUID}`.
As of this …

ci: add codspeed to benchmark ANTA

---

.vscode/settings.json
tests/benchmark/conftest.py
tests/benchmark/test_anta.py
tests/benchmark/test_runner.py
tests/conftest.py
tests/units/conftest.py

Add benchmarks for synchronous functions `anta.runner.get_coroutines` and `anta.runner.prepare_tests`.

ci: add prepare_tests and get_coroutines benchmarks

---

anta/device.py
tests/units/test_device.py

feat: Log when show version modelName is an empty string

---

anta/cli/_main.py

without this we get
```
ANTA_VERSION=42 anta get tags
Usage: anta [OPTIONS] COMMAND [ARGS]...
Try 'anta --help' for help.
Error: Invalid value for '--version': '42' is not a valid boolean.
ANTA_HELP=42 anta get tags
Usage: anta [OPTIONS] COMMAND [ARGS]...
Try 'anta --help' for help.
Error: Invalid value for '--help': '42' is not a valid boolean.
```
Fixes #868

fix(anta.cli): Disable env variable for --help and --version

---

anta/tests/security.py
tests/units/anta_tests/test_security.py

EOS 4.32 changed the text output of `show management ssh`, breaking our existing logic. New logic handles both pre and post 4.32 outputs.

fix(anta.tests): Fix VerifySSHStatus to support 4.32 text output

---

anta/custom_types.py
anta/tests/snmp.py
examples/tests.yaml
tests/units/anta_tests/test_snmp.py

Verifies the number of SNMP error counter(s) processed.
By default, all  error counters will be checked for any non-zero values.
An optional list of specific error counters can be provided for granular testing.
* Success: The test will pass if the SNMP error counter(s) are zero/None.
* Failure: The test will fail if the SNMP error counter(s) are non-zero/not None/Not Found or is not configured.
Fixes #834

feat(anta): Added the test case to verify SNMP error counters

---

anta/reporter/__init__.py
anta/reporter/md_reporter.py
docs/advanced_usages/as-python-lib.md
docs/advanced_usages/custom-tests.md
docs/api/csv_reporter.md
docs/api/md_reporter.md
docs/api/reporters.md
docs/api/tests.md
docs/api/tests.routing.bgp.md
docs/api/tests.routing.isis.md
docs/api/tests.routing.ospf.md
docs/cli/debug.md
docs/cli/get-inventory-information.md
docs/cli/nrfu.md
docs/cli/tag-management.md
docs/faq.md
docs/stylesheets/extra.material.css
docs/usage-inventory-catalog.md
examples/README.md
examples/merge_catalogs.py
examples/parse_anta_inventory_file.py
examples/run_eos_commands.py
mkdocs.yml
pyproject.toml

doc: Clean doc pre-release

---

anta/cli/nrfu/utils.py
tests/data/test_catalog_double_failure.yml
tests/units/cli/conftest.py
tests/units/cli/nrfu/test_commands.py

Print multiple messages in text output when present
```
leaf1 :: VerifyInterfacesSpeed :: FAILURE
Interface `Ethernet2` is not found.
Interface `Ethernet3` is not found.
Interface `Ethernet4` is not found.
```
Fixes #895

fix(anta.cli): Print multiple messages for anta nrfu text

---

anta/runner.py
docs/cli/tag-management.md
tests/data/test_inventory_with_tags.yml
tests/units/test_runner.py

#827 fixed multiple `--tags` CLI support but introduced an issue where test-to-device tag matching wasn't properly enforced.
This PR now reflects the behavior specified in the [Tag Management ](https://anta.arista.com/stable/cli/tag-management/#using-tags) documentation.

fix(anta)!: Fix tags behavior to reflect the documentation

---

anta/input_models/__init__.py
anta/input_models/connectivity.py
anta/tests/connectivity.py
docs/api/tests.connectivity.md
docs/templates/python/material/anta_test_input_model.html.jinja
docs/templates/python/material/class.html.jinja
tests/units/anta_tests/test_connectivity.py

fix(anta.tests): Fix VerifyReachability failure messages

---

anta/cli/exec/commands.py
anta/cli/exec/utils.py
docs/cli/exec.md

ANTA should not configure the devices - only outputing a nice error message when something is missing
Fixes #894

refactor: Deprecate the ability to configure aaa config when collecting show-techs

---

anta/input_models/__init__.py
anta/input_models/system.py
anta/tests/system.py
docs/api/tests.system.md
tests/units/anta_tests/test_system.py

Update VerifyNTPAssociations test to support IP-DNS peers in the JSON output. We now check if the provided NTP server IP or DNS is matching either the peer key or `peerIpAddr` in the details.
Fixes #900

fix(anta.tests): Fix VerifyNTPAssociations to support IP-DNS peers

---

anta/tests/logging.py

Update:
- VerifyLoggingTimestamp
- VerifyLoggingHostname
- VerifyLoggingLogsGeneration
To specify that the tests will work only when EOS is configured with logging buffer secerity level info or higher.

doc(anta.tests): Update logging tests docstrings for clarity

---

docs/cli/inv-from-ansible.md

Cleaner doc that makes sense
Fixes #911

doc: Clean documentation for inv-from-ansible

---

pyproject.toml

Need to install a fork of respx until https://github.com/lundberg/respx/issues/277 is fixed.

ci: Add support for HTTPX 0.28

---

anta/tests/routing/bgp.py
docs/advanced_usages/custom-tests.md
tests/units/anta_tests/routing/test_bgp.py

`peerTcpInfo` key is not present in the BGP output if the session is not `Established` so we need to skip that check in the logic.

fix(anta.tests): Fix BGP tests failures

---

docs/api/tests.routing.bgp.md

fix(anta.tests): Add note about multi-agent in BGP tests

---

anta/decorators.py
anta/input_models/stun.py
anta/tests/stun.py
docs/api/tests.stun.md
examples/tests.yaml
tests/units/anta_tests/test_stun.py
tests/units/cli/get/test_commands.py
tests/units/test_decorators.py

Refactoring STUN tests module to address the following issues:
- https://github.com/aristanetworks/anta/issues/809
- https://github.com/aristanetworks/anta/issues/587
- https://github.com/aristanetworks/anta/issues/388

fix(anta.tests): Cleaning up STUN tests module

---

anta/input_models/interfaces.py
anta/tests/interfaces.py
examples/tests.yaml
tests/units/anta_tests/test_interfaces.py
tests/units/input_models/test_interfaces.py

Refactoring Interfaces tests module to address the following issues:
- https://github.com/aristanetworks/anta/issues/809
- https://github.com/aristanetworks/anta/issues/587
- https://github.com/aristanetworks/anta/issues/388

fix(anta.tests): Cleaning up Interfaces tests module (VerifyLACPInterfacesStatus)

---

anta/tests/cvx.py
tests/units/anta_tests/test_cvx.py

Test is throwing error when run on a a device not running CVX at all. Looking at the unit tests, it feels the revision for the command should be `3` and not `1` (cf issue comments)
Fixes #953

fix(anta.tests): Adjust revision for show management cvx

---

anta/tests/cvx.py
examples/tests.yaml
tests/units/anta_tests/test_cvx.py

Verifies the number of active cvx connections to match the expected active cvx connections .

feat(anta): Add test catalog to verify active CVX connections

---

docs/advanced_usages/as-python-lib.md
docs/advanced_usages/custom-tests.md
docs/cli/debug.md
docs/cli/exec.md
docs/cli/get-inventory-information.md
docs/cli/get-tests.md
docs/cli/inv-from-ansible.md
docs/cli/inv-from-cvp.md
docs/cli/nrfu.md
docs/cli/overview.md
docs/cli/tag-management.md
docs/contribution.md
docs/requirements-and-installation.md
docs/troubleshooting.md
docs/usage-inventory-catalog.md
mkdocs.yml
pyproject.toml

Add support to convert Github Admonitions to basic mkdocs admonitions using [`PGijsbers/admonitions`](https://github.com/PGijsbers/admonitions). This conversion helps to get nice document in both worlds: Github and Mkdocs.

doc: Add gh-admonition plugin

---

anta/constants.py
anta/device.py
anta/models.py
pyproject.toml
tests/units/test_device.py
tests/units/test_models.py

Add a list of known errors from EOS to match on to decide a test status
Fixes #952 
Fixes #954

feat(anta.tests): Add known EOS errors as failure

---

anta/tests/routing/bgp.py
tests/units/anta_tests/routing/test_bgp.py

Updated the test to at least one EVPN route has at least one active/valid path across all learned routes from all RDs combined
Fixes #950

fix(anta.tests): VerifyEVPNType2Route test fails for locally originated MAC/IP addresses

---

anta/tests/interfaces.py
examples/tests.yaml
tests/units/anta_tests/test_interfaces.py

Use correct type for inputs
Fixes #973

fix(anta.tests): Fix wrong type used for inputs for VerifyInterfaceIPv4

---

anta/cli/get/commands.py
anta/cli/get/utils.py
tests/units/cli/get/test_commands.py

Catch OSErrors when writing inv
Fixes #772

fix(anta.cli): Better error handling for OSError when writing inventory

---

anta/tests/stp.py
examples/tests.yaml
tests/units/anta_tests/test_stp.py

This test performs the following checks:
1. Verifies that the STP is configured.
2. Verifies that the specified VLAN is present on the device.
3. Verifies that the STP is disabled for the specified VLANs.
* Success: The test will pass if STP is disabled for the specified VLANs.
* Failure: The test will fail, if STP is enabled for the specified VLANs
Fixes  #862

feat(anta): Added testcase to validate the STP disabled VLANs

---

anta/input_models/routing/bgp.py
anta/tests/routing/bgp.py
examples/tests.yaml
tests/units/anta_tests/routing/test_bgp.py

feat(anta.tests): Add VerifyBGPPeerSession + minor fixes on other BGP tests 

---

anta/logger.py
tests/units/test_logger.py

Great news everyone - it is now MUCH faster to run the tests.. Locally it means 9s vs 74s for my machine.
The issue was that we were adding too many RichHandler when calling CliRunner multiple times...
**NOTE:** Logging need some more love.

test: idempotency of setup logger

---

anta/cli/utils.py
tests/data/invalid_inventory.yml
tests/units/cli/nrfu/test__init__.py

log exceptions in CLI
Fixes #986

feat(anta.cli): Better error message when invalid inventory or catalogs are parsed

---

anta/input_models/snmp.py
anta/tests/snmp.py
docs/api/tests.snmp.md
examples/tests.yaml
tests/units/anta_tests/test_snmp.py

This test performs the following checks for each specified host:
1. Verifies that the SNMP logging is enabled on the device.
2. Verifies SNMP host matches the expected value.
3. Ensures that VRF provided matches the expected value.
* Success: The test will pass if all of the following conditions are met:
- The SNMP logging is enabled on the device.
- The SNMP host matches the expected value.
- The VRF provided matches the expected value.
* Failure: The test will fail if any of the following conditions is met:
- The SNMP logging is disabled on the device.
- The SNMP host do not matches the expected value.
- The VRF provided do not matches the expected value.
Fixes #821

feat(anta): Added the test case to verify SNMP Logging Configuration

---

anta/tests/bfd.py
tests/units/input_models/test_bfd.py

BFD test module: AntaTest.Input subclasses using common input models should have validators for their required fields.
Fixes #997

fix(anta.tests): BFD test module: AntaTest.Input subclasses using common input models should have validators for their required fields.

---

anta/constants.py
anta/models.py
anta/tests/profiles.py
tests/units/anta_tests/test_profiles.py

fix(anta.tests): VerifyUnifiedForwardingTableMode test is now skipped on unsupported platforms

---

anta/input_models/routing/bgp.py
anta/input_models/routing/generic.py
anta/tests/interfaces.py
anta/tests/routing/generic.py
tests/units/input_models/routing/test_generic.py
tests/units/input_models/test_interfaces.py

AntaTest.Input subclasses using common input models should have validators for their required fields.
- input_models/bgp : `route_type` marked as required key and no reuse.
- tests/interfaces.py : Added validators for `status` field in VerifyInterfacesStatus test
- tests/interfaces.py : Added validators for `portchannel ` field in VerifyLACPInterfacesStatus test
- tests/routing/generic.py : Added validators for `route_type ` field in VerifyIPv4RouteType test

fix(anta.tests): AntaTest.Input subclasses using common input models should have validators for their required fields.

---

anta/tests/logging.py
anta/tests/security.py
examples/tests.yaml
tests/units/anta_tests/test_logging.py
tests/units/anta_tests/test_security.py

Updated failure messages for following tests
1. test_logging.py
1. VerifyLoggingHosts
2. test_security.py
1. VerifySSHIPv4Acl
2. VerifySSHIPv6Acl
3. VerifyAPIHttpsSSL
4. VerifyAPIIPv4Acl 
5. VerifyAPIIPv6Acl    
Fixes # (issue id) #587

refactor(anta.tests): Nicer result failure messages for Logging and security test module

---

anta/tests/routing/generic.py
tests/units/anta_tests/routing/test_generic.py

Updated failure messages for following tests
1. VerifyRoutingTableSize
2. VerifyRoutingTableEntry
Fixes #587

refactor(anta.tests): Nicer result failure messages generic routing module

---

anta/input_models/connectivity.py
anta/tests/bfd.py
tests/units/anta_tests/test_bfd.py
tests/units/anta_tests/test_connectivity.py

Updated failure messages for following tests
1. test_bfd.py
1. VerifyBFDPeersRegProtocols
2. test_connectivity.py
1. VerifyReachability
2. VerifyLLDPNeighbors
Fixes #587

refactor(anta.tests): Nicer result failure messages BFD & Connectivity test module

---

anta/tests/vxlan.py
examples/tests.yaml
tests/units/anta_tests/test_vxlan.py

Nicer result failure messages Vxlan test module
Fixes #587

refactor(anta.tests): Nicer result failure messages Vxlan test module

---

anta/input_models/avt.py
anta/tests/avt.py
anta/tests/field_notices.py
tests/units/anta_tests/test_avt.py
tests/units/anta_tests/test_field_notices.py

Nicer result failure messages  for following test module.
1. AVT, 
2. field_notice 
**Note:** Test with unit test only, as this testcases are skipped on ATD lab
Fixes #587

refactor(anta.tests): Nicer result failure messages AVT, field_notice test module 

---

anta/input_models/services.py
anta/tests/services.py
anta/tests/snmp.py
tests/units/anta_tests/test_services.py
tests/units/anta_tests/test_snmp.py

1.  Service
2.  SNMP
Fixes #587

refactor(anta.tests): Nicer result failure messages Service and SNMP test module 

---

anta/tests/ptp.py
anta/tests/software.py
examples/tests.yaml
tests/units/anta_tests/test_ptp.py
tests/units/anta_tests/test_software.py

1 . PTP
2.  Software
**Note:** Test with unit test only, as this testcases are skipped on ATD lab
Fixes https://github.com/aristanetworks/anta/issues/587

refactor(anta.tests): Nicer result failure messages PTP, software test module

---

anta/input_models/routing/isis.py
anta/tests/routing/isis.py
tests/units/anta_tests/routing/test_isis.py
tests/units/input_models/routing/test_isis.py

Refactor VerifyISISSegmentRoutingTunnels test case
Fixes #388

refactor(anta.tests): Refactor VerifyISISSegmentRoutingTunnels test case

---

.pre-commit-config.yaml
anta/cli/nrfu/__init__.py
anta/cli/nrfu/commands.py
docs/cli/nrfu.md
docs/getting-started.md
docs/imgs/anta_debug_help.svg
docs/imgs/anta_help.svg
docs/imgs/anta_nrfu_csv_help.svg
docs/imgs/anta_nrfu_help.svg
docs/imgs/anta_nrfu_json_help.svg
docs/imgs/anta_nrfu_mdreport_help.svg
docs/imgs/anta_nrfu_table_help.svg
docs/imgs/anta_nrfu_text_help.svg
docs/imgs/anta_nrfu_tplreport_help.svg
docs/scripts/__init__.py
docs/scripts/generate_doc_snippets.py
docs/scripts/generate_snippet.py
docs/snippets/anta_debug_help.txt
docs/snippets/anta_help.txt
docs/snippets/anta_nrfu_csv_help.txt
docs/snippets/anta_nrfu_help.txt
docs/snippets/anta_nrfu_json_help.txt
docs/snippets/anta_nrfu_mdreport_help.txt
docs/snippets/anta_nrfu_table_help.txt
docs/snippets/anta_nrfu_text_help.txt
docs/snippets/anta_nrfu_tplreport_help.txt

bonus 🎈:
* precise doc for JSON
* auto generate docs for some CLI (TBC)
Fixes #1049

fix(anta.cli): Make CSV output file option mandatory

---

anta/device.py

Add a Semaphore of 100 per device to avoid sending too many commands/requests to HTTPX. HTTPX has a default max_connections of 100 so we respect that to avoid high-concurrency performance issues.
Related to:
https://github.com/encode/httpx/issues/3215
https://github.com/encode/httpcore/pull/928
https://github.com/encode/httpcore/pull/929
Benchmarks on i7-12800H, 32GB RAM, 1048576 file descriptors
**With Semaphore**:
```
2025-02-13 17:28:22,109 - INFO - Running benchmarks with 64 commands and max_connections=100
2025-02-13 17:28:22,110 - INFO - <172.20.20.111>: Starting benchmarks...
2025-02-13 17:28:22,110 - INFO - <172.20.20.111>: Benchmarking with batch size 1
2025-02-13 17:28:23,602 - INFO - <172.20.20.111>: Completed benchmarking with batch size 1 in 1.492405 seconds
2025-02-13 …
```

fix(anta): Add Semaphore to AsyncEOSDevice

---

anta/input_models/system.py
anta/tests/stp.py
anta/tests/system.py
examples/tests.yaml
tests/units/anta_tests/test_stp.py
tests/units/anta_tests/test_system.py

refactor(anta.tests): Nicer result failure messages STP and System test module 

---

anta/input_models/connectivity.py
anta/tests/connectivity.py
examples/tests.yaml
tests/units/anta_tests/test_connectivity.py

Added Negative testing in VerifyReachability
Added `reachable: bool = True` to the input model, Indicates whether the destination should be reachable. Set to True if the network should be accessible, False otherwise.
Validated with the unit tests.
Fixes #1047

feat(anta.tests): Added negative testing in VerifyReachability test

---

anta/input_models/interfaces.py
anta/tests/interfaces.py
tests/units/anta_tests/test_interfaces.py
tests/units/input_models/test_interfaces.py

Modular switches have Ethernet X/X naming scheme. Could also be Ethernet X/X/X for multi-lane ports on modular switches.
Use AntaCommand with `show ip interface` command to fetch all interfaces and fail the test if any of the provided interface is not found.
Fixes #1051

fix(anta.tests): VerifyIPProxyARP and VerifyInterfaceIPv4 tests for 'Incomplete command' error

---

anta/tests/mlag.py
tests/units/anta_tests/test_mlag.py

Nicer result failure messages MLAG test module 
Fixes #587

refactor(anta.tests): Nicer result failure messages MLAG test module 

---

anta/tests/hardware.py
tests/units/anta_tests/test_hardware.py

1. Hardware 
**Note**: Test with the Unit tests only, not able to test on ATD lab.
Fixes https://github.com/aristanetworks/anta/issues/587

refactor(anta.tests): Nicer result failure messages hardware test module

---

anta/tests/interfaces.py
tests/units/anta_tests/test_interfaces.py

Nicer result failure messages Interface test module following testcases are covers.
1. VerifyInterfaceUtilization
2. VerifyInterfaceErrors
3. VerifyInterfaceDiscards
4. VerifyInterfaceErrDisabled
5. VerifyInterfacesStatus
6. VerifyStormControlDrops
Fixes #587

refactor(anta.tests): Nicer result failure messages interface(part -1) test module 

---

anta/reporter/md_reporter.py
tests/data/test_md_report.md
tests/units/result_manager/conftest.py
tests/units/result_manager/test__init__.py
tests/units/result_manager/test_files/test_md_report_results.json

Updated `anta/reporter/md_reporter.py` with adding fix for Multiple failure messages not rendered properly in the Markdown report
Tested the change with considering `https://github.com/aristanetworks/anta/blob/main/examples/tests.yaml` 
Fixes #1055

fix(anta): fixed Multiple failure messages not rendered properly in the Markdown report

---

anta/tests/routing/ospf.py
examples/tests.yaml
tests/units/anta_tests/routing/test_ospf.py

refactor(anta.tests): Nicer result failure messages OSPF test module 

---

anta/tests/interfaces.py
tests/units/anta_tests/test_interfaces.py

Nicer result failure messages Interface test module following testcases are covers.
1. VerifyPortChannels
2. VerifyIllegalLACP
3. VerifyLoopbackCount
4. VerifySVI
5. VerifyL3MTU
6. VerifyIPProxyARP
Fixes #587

refactor(anta.tests): Nicer result failure messages interface(part-2) test module 

---

anta/catalog.py
anta/result_manager/__init__.py
pyproject.toml

Fixes #754
Add typing_extensions until the lowest supported version is .. 3.13 ;)

chore(anta): Add deprecation on deprecated method

---

.pre-commit-config.yaml
asynceapi/_constants.py
asynceapi/_errors.py
asynceapi/_models.py
asynceapi/_types.py
asynceapi/device.py
pyproject.toml
tests/units/asynceapi/test__constants.py
tests/units/asynceapi/test__models.py
tests/units/asynceapi/test_data.py
tests/units/asynceapi/test_device.py

Adding internal modules to asynceapi to support request/response models when executing commands on eAPI.
The goal is to have a consistent response model with whatever eAPI JSON-RPC params we use in the requests.
New models now support `timestamps` and `stopOnError` eAPI features properly.

feat(anta): Add EapiRequest and EapiResponse models for asynceapi to support eAPI stopOnError and timestamps features

---

anta/cli/exec/utils.py

cf title
Fixes #808
Today we are not testing this function but won't do this in this PR as we will be dropping some functionality in 2.0.0

refactor(anta.cli): Better error message when asyncssh is unable to verify host key

---

anta/input_models/cvx.py
anta/tests/stp.py
docs/api/tests/cvx.md

Fixed documentation issue for VerifySTPdisabledVlanTest  and CVX input model
Fixes #1104

doc(anta.tests): Fixed documentation issue for VerifySTPdisabledVlan and CVX input model

---

anta/result_manager/__init__.py
tests/data/test_md_report.md
tests/units/result_manager/test__init__.py
tests/units/result_manager/test_files/test_md_report_results.json

anta/anta/result_manager/__init__.py", line 298, in sort
self._result_entries.sort(key=lambda result: [getattr(result, field) for field in sort_by])
~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '<' not supported between instances of 'NoneType' and 'str'
Fixes #1110

fix(anta): Fixing the TypeError: '<' not supported between instances of 'NoneType' and 'str'

---

anta/input_models/connectivity.py
anta/tests/connectivity.py
examples/tests.yaml
tests/units/anta_tests/test_connectivity.py

When source is None, that means we don't provide a source to the ping command and let EOS decides the source.
Fixes #1112

feat(anta.tests): The source field of VerifyReachability Host model should be optional

---

anta/decorators.py
anta/tests/cvx.py
anta/tests/flow_tracking.py
anta/tests/snmp.py
anta/tests/system.py
anta/tests/vxlan.py
examples/tests.yaml
tests/units/anta_tests/test_flow_tracking.py
tests/units/anta_tests/test_system.py
tests/units/anta_tests/test_vxlan.py

Updated failure messages, updated skip_on_platforms decorator message

refactor(anta): Updated failure messages, updated skip_on_platforms decorator message

---

anta/runner.py
tests/units/test_runner.py

Catch ValueError in call to setrlimit if can't set RLIMIT_NOFILE
Fixes #1135

fix(anta): Catch ValueError in call to setrlimit if can't set RLIMIT_NOFILE.

---

anta/device.py
asynceapi/device.py
tests/conftest.py
tests/units/cli/conftest.py
tests/units/test_device.py

Use HTTP HEAD request to check connection to a device instead of pure L3 check.
This allows to check connectivity on devices behind a reverse proxy, so rather than checking the reverse proxy is alive using HTTP the request will be forwarded to the right device.
The change is as close to the original as possible, but we could potentially check if the credentials are correct as well.

feat(anta)!: Use HTTP HEAD request instead of a TCP connection to check if device is online

---

anta/tests/logging.py
tests/units/anta_tests/test_logging.py

VerifyLoggingErrors failure message should include the error logs
Fixes #1139

feat(anta.tests): VerifyLoggingErrors failure message should include the error logs

---

docs/contribution.md

Updated the contribution readme with the following changes:
1. Added a note to advise users using terminals like zsh to enclose commands in quotes to ensure correct interpretation. This addresses potential issues with how zsh handles certain special characters.
2. Included a note to clarify that the installation verification command (pip list -e) should be run from within the inner anta directory after performing the editable install. This addresses a scenario where users might not see any output if the command is run from the top-level repository directory.

doc: Update contribution README with notes on quoting and verification path

---

pyproject.toml

cf https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#license + deprecation warnings when running build

ci: Update pyproject to new license format

---

anta/custom_types.py
anta/input_models/routing/bgp.py
anta/tests/routing/bgp.py
examples/tests.yaml
tests/units/anta_tests/routing/test_bgp.py

Extend BgpPeer model to support an optional list of communities and check against those instead of all.
advertised_communities: list[Community] = Field(default=["standard', "extended', "large"
Fixes #1173

feat(anta_tests): VerifyBGPAdvCommunities support a combination of communities

---

anta/tests/evpn.py
examples/tests.yaml

```
CRITICAL Test catalog is invalid! (from examples/tests.yaml)                                                                 logger.py:151
ValidationError: 1 validation error for AntaCatalogFile                                                                          
inputs                                                                                                                           
VerifyEVPNType5Routes test inputs are not valid: 1 validation error for Input                                                  
prefixes.3.routes.0.paths.0.route_targets.0                                                                              
Input should be a valid string
```

doc(anta): fixed the invalid catalog due to evpn-type-5 docstring

---

anta/reporter/md_reporter.py
anta/tests/logging.py
examples/tests.yaml
tests/data/test_md_report.md
tests/data/test_md_report_custom_sections.md
tests/units/anta_tests/test_logging.py
tests/units/result_manager/test__init__.py
tests/units/result_manager/test_files/test_md_report_results.json

Special characters from failure messages should be escaped properly in Markdown
Fixes #1090

refactor(anta): Special characters from failure messages should be escaped properly in Markdown

---

anta/cli/nrfu/commands.py
anta/cli/nrfu/utils.py
anta/constants.py
anta/reporter/md_reporter.py
tests/data/test_md_report_extra_data.md
tests/units/reporter/test_md_reporter.py
tests/units/result_manager/conftest.py

Enhance MDReportGenerator to support an optional `extra_data` dictionary to add additional data that can be used by section generators.
The extra_data will be used by ANTA CLI to add the run information and generate the `Run Overview` section of the report.
Fixes #1208

feat(anta): Add Run Overview section to Markdown report including unreachable/filtered devices from the run

---

pyproject.toml
tests/benchmark/test_anta.py

Bump pytest-asyncio minimum version to v1.0.0 and update benchmarks. New version doesn't support the `event_loop` fixture anymore: https://pytest-asyncio.readthedocs.io/en/stable/how-to-guides/migrate_from_0_21.html

bump: Update code to support pytest-asyncio v1.0.0

---

anta/_runner.py
asynceapi/device.py
tests/units/test__runner.py

Remove the use of `anta.cli.console` in the runner to avoid being dependant of `anta.cli` when using ANTA as a library.
Fixes #1226

fix(anta): Remove anta.cli import from anta._runner

---

anta/tests/routing/ospf.py
tests/units/anta_tests/routing/test_ospf.py

The current failure message:
Instance: 100 VRF: default Interface: 10.1.0.1 - Incorrect adjacency state - Expected: full Actual: exchStart which is incorrect since 10.1.0.1 is the router ID of its neighbor, not the interface.
It should be:
Instance: 100 VRF: default Neighbor ID: 10.1.0.1 - Incorrect adjacency state - Expected: full Actual: exchStart
Fixes #1204

fix(anta.tests): VerifyOSPFNeighborState displays the wrong failure message

---

anta/tests/connectivity.py
tests/units/anta_tests/test_connectivity.py

If the source IP is not present on any interfaces, EOS will output the following:
DC1-LEAF1A#ping vrf default fd12:3456:789a:1::2 source fd12:3456:789a:1::1 size 100 df-bit repeat 2
ping: bind icmp socket: Cannot assign requested address
DC1-LEAF1A#ping vrf default 8.8.8.8 source 1.2.3.4
ping: bind: Cannot assign requested address
Fixes #1241

fix(anta.tests): False positives in VerifyReachability

---

anta/tests/hardware.py
tests/units/anta_tests/test_hardware.py

fix(anta.tests): Fix input variable typo in VerifySupervisorRedundancy

---

anta/tests/hardware.py
tests/units/anta_tests/test_hardware.py

Update VerifyTemperature to support a failure_margin as input
Fixes #1279

fix(anta.tests): Update VerifyTemperature to support a failure_margin as input

---

anta/constants.py

Added fix PTP tests not supported on certain hardware platform
Fixes #1298

fix(anta.tests): Added fix PTP tests not supported on certain hardware platform

---

anta/tests/services.py
tests/units/anta_tests/test_services.py

Added fix for VerifyErrdisableRecovery errors out when timer interval is N/A
Fixes #1296

fix(anta.tests): Added fix for VerifyErrdisableRecovery errors out when timer interval is N/A

---

anta/tests/logging.py
tests/units/anta_tests/test_logging.py

Enhanced VerifyLoggingErrors to support the last N of units
Fixes #1309

feat(anta): Enhanced VerifyLoggingErrors to support the last N of units

---

.pre-commit-config.yaml
pyproject.toml

Unlocking us until this is addressed: https://github.com/CodSpeedHQ/pytest-codspeed/issues/89

ci: Cap pytest-codspeed for now because pre-commit is sad on OSX
